
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1123 ?s1 ;
		wdt:P1148 ?z1 ;
		wdt:P2114 ?h1 ;
		wdt:P1122 ?j1 .

}
