
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1457 ?l1 ;
		wdt:P2248 ?c1 ;
		wdt:P2045 ?o1 ;
		wdt:P1096 ?g1 ;
		wdt:P2325 ?b1 ;
		wdt:P2233 ?y1 ;
		wdt:P4501 ?w1 .

}
