
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1457 ?c1 ;
		wdt:P2244 ?k1 ;
		wdt:P2213 ?z1 ;
		wdt:P2045 ?l1 ;
		wdt:P2325 ?w1 ;
		wdt:P2233 ?j1 .

}
