
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2146 ?q1 ;
		wdt:P1457 ?k1 ;
		wdt:P2248 ?z1 ;
		wdt:P2244 ?y1 ;
		wdt:P2243 ?g1 ;
		wdt:P2213 ?m1 ;
		wdt:P2045 ?n1 ;
		wdt:P2325 ?c1 .

}
