
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2213 ?w1 ;
		wdt:P1457 ?r1 ;
		wdt:P4501 ?g1 ;
		wdt:P2243 ?l1 ;
		wdt:P2325 ?m1 .

}
