
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2146 ?p1 ;
		wdt:P1457 ?c1 ;
		wdt:P2045 ?k1 ;
		wdt:P2243 ?e1 ;
		wdt:P2248 ?u1 .

}
