
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2146 ?r1 ;
		wdt:P1457 ?e1 ;
		wdt:P2244 ?v1 ;
		wdt:P2213 ?y1 ;
		wdt:P1096 ?t1 ;
		wdt:P2325 ?i1 ;
		wdt:P2233 ?u1 .

}
