
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2146 ?g1 ;
		wdt:P2244 ?q1 ;
		wdt:P2233 ?f1 ;
		wdt:P2243 ?z1 ;
		wdt:P2325 ?w1 .

}
