
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2146 ?i1 ;
		wdt:P2045 ?u1 ;
		wdt:P1096 ?a1 ;
		wdt:P2233 ?h1 ;
		wdt:P4501 ?z1 .

}
