
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1457 ?t1 ;
		wdt:P2248 ?e1 ;
		wdt:P2244 ?y1 ;
		wdt:P2045 ?d1 ;
		wdt:P1096 ?p1 ;
		wdt:P2325 ?k1 .

}
