
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1457 ?u1 ;
		wdt:P2248 ?c1 ;
		wdt:P2243 ?m1 ;
		wdt:P2325 ?z1 .

}
