
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1457 ?w1 ;
		wdt:P2248 ?i1 ;
		wdt:P2244 ?z1 ;
		wdt:P2213 ?j1 ;
		wdt:P2045 ?p1 ;
		wdt:P2325 ?g1 ;
		wdt:P2233 ?y1 ;
		wdt:P4501 ?d1 .

}
