
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P2146 ?n1 ;
		wdt:P4501 ?x1 ;
		wdt:P2244 ?y1 ;
		wdt:P2243 ?d1 ;
		wdt:P2213 ?m1 ;
		wdt:P2045 ?o1 ;
		wdt:P1096 ?b1 .

}
