
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT (COUNT(*) AS ?c) WHERE {
	?id1 wdt:P1457 ?o1 ;
		wdt:P4501 ?s1 ;
		wdt:P2244 ?a1 ;
		wdt:P2213 ?f1 ;
		wdt:P2045 ?g1 ;
		wdt:P2233 ?q1 .

}
