
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?v1 ;
		wdt:P4501 ?y1 ;
		wdt:P2244 ?d1 ;
		wdt:P2243 ?l1 ;
		wdt:P2213 ?e1 ;
		wdt:P2045 ?f1 ;
		wdt:P2325 ?q1 ;
		wdt:P2248 ?x1 .

}
CLUSTER BY ?v1 ?y1 ?d1 ?l1 ?e1 ?f1 ?q1 ?x1 WITH %s AS ?c
