
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?t1 ;
		wdt:P2233 ?m1 ;
		wdt:P4501 ?f1 ;
		wdt:P2243 ?w1 ;
		wdt:P2045 ?z1 .

}
CLUSTER BY ?t1 ?m1 ?f1 ?w1 ?z1 WITH %s AS ?c
