
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?r1 ;
		wdt:P2248 ?a1 ;
		wdt:P2244 ?x1 ;
		wdt:P2045 ?d1 ;
		wdt:P1096 ?c1 ;
		wdt:P2325 ?v1 ;
		wdt:P2233 ?p1 ;
		wdt:P4501 ?s1 .

}
CLUSTER BY ?r1 ?a1 ?x1 ?d1 ?c1 ?v1 ?p1 ?s1 WITH %s AS ?c
