
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?f1 ;
		wdt:P4501 ?g1 ;
		wdt:P2213 ?q1 ;
		wdt:P2045 ?o1 ;
		wdt:P2325 ?s1 ;
		wdt:P2233 ?a1 .

}
CLUSTER BY ?f1 ?g1 ?q1 ?o1 ?s1 ?a1 WITH %s AS ?c
