
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?f1 ;
		wdt:P1457 ?h1 ;
		wdt:P2248 ?l1 ;
		wdt:P2045 ?e1 ;
		wdt:P1096 ?w1 ;
		wdt:P2325 ?z1 ;
		wdt:P2233 ?a1 .

}
CLUSTER BY ?f1 ?h1 ?l1 ?e1 ?w1 ?z1 ?a1 WITH %s AS ?c
