
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?m1 ;
		wdt:P1457 ?q1 ;
		wdt:P2248 ?r1 ;
		wdt:P2213 ?j1 ;
		wdt:P2045 ?h1 ;
		wdt:P1096 ?p1 ;
		wdt:P2325 ?c1 ;
		wdt:P4501 ?a1 .

}
CLUSTER BY ?m1 ?q1 ?r1 ?j1 ?h1 ?p1 ?c1 ?a1 WITH %s AS ?c
