
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P4501 ?o1 ;
		wdt:P2244 ?j1 ;
		wdt:P2243 ?d1 ;
		wdt:P1096 ?b1 ;
		wdt:P2325 ?r1 ;
		wdt:P2233 ?g1 .

}
CLUSTER BY ?o1 ?j1 ?d1 ?b1 ?r1 ?g1 WITH %s AS ?c
