
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?i1 ;
		wdt:P1457 ?v1 ;
		wdt:P4501 ?q1 ;
		wdt:P2244 ?y1 ;
		wdt:P2213 ?z1 ;
		wdt:P1096 ?f1 ;
		wdt:P2325 ?d1 .

}
CLUSTER BY ?i1 ?v1 ?q1 ?y1 ?z1 ?f1 ?d1 WITH %s AS ?c
