
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2213 ?z1 ;
		wdt:P1457 ?j1 ;
		wdt:P2325 ?q1 ;
		wdt:P4501 ?s1 ;
		wdt:P2248 ?o1 .

}
CLUSTER BY ?z1 ?j1 ?q1 ?s1 ?o1 WITH %s AS ?c
