
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2248 ?g1 ;
		wdt:P2244 ?i1 ;
		wdt:P2243 ?h1 ;
		wdt:P2213 ?d1 ;
		wdt:P2325 ?r1 ;
		wdt:P2233 ?b1 .

}
CLUSTER BY ?g1 ?i1 ?h1 ?d1 ?r1 ?b1 WITH %s AS ?c
