
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?n1 ;
		wdt:P1457 ?h1 ;
		wdt:P4501 ?a1 ;
		wdt:P2045 ?k1 .

}
CLUSTER BY ?n1 ?h1 ?a1 ?k1 WITH %s AS ?c
