
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?o1 ;
		wdt:P4501 ?m1 ;
		wdt:P2244 ?l1 ;
		wdt:P2243 ?t1 ;
		wdt:P2045 ?i1 ;
		wdt:P1096 ?d1 ;
		wdt:P2325 ?q1 ;
		wdt:P2248 ?w1 .

}
CLUSTER BY ?o1 ?m1 ?l1 ?t1 ?i1 ?d1 ?q1 ?w1 WITH %s AS ?c
