
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P4501 ?s1 ;
		wdt:P2244 ?r1 ;
		wdt:P2243 ?d1 ;
		wdt:P2213 ?i1 ;
		wdt:P2045 ?n1 ;
		wdt:P1096 ?y1 .

}
CLUSTER BY ?s1 ?r1 ?d1 ?i1 ?n1 ?y1 WITH %s AS ?c
