
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2244 ?v1 ;
		wdt:P2045 ?l1 ;
		wdt:P2233 ?y1 ;
		wdt:P2243 ?a1 ;
		wdt:P2325 ?n1 .

}
CLUSTER BY ?v1 ?l1 ?y1 ?a1 ?n1 WITH %s AS ?c
