
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?j1 ;
		wdt:P1096 ?q1 ;
		wdt:P2233 ?w1 ;
		wdt:P2243 ?v1 .

}
CLUSTER BY ?j1 ?q1 ?w1 ?v1 WITH %s AS ?c
