
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?c1 ;
		wdt:P1457 ?d1 ;
		wdt:P2248 ?x1 ;
		wdt:P2244 ?q1 ;
		wdt:P2243 ?w1 ;
		wdt:P2213 ?e1 ;
		wdt:P2233 ?i1 ;
		wdt:P4501 ?j1 .

}
CLUSTER BY ?c1 ?d1 ?x1 ?q1 ?w1 ?e1 ?i1 ?j1 WITH %s AS ?c
