
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P4501 ?d1 ;
		wdt:P2244 ?i1 ;
		wdt:P2243 ?o1 ;
		wdt:P2045 ?v1 ;
		wdt:P1096 ?a1 ;
		wdt:P2248 ?r1 .

}
CLUSTER BY ?d1 ?i1 ?o1 ?v1 ?a1 ?r1 WITH %s AS ?c
