
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?t1 ;
		wdt:P2213 ?n1 ;
		wdt:P2233 ?a1 ;
		wdt:P2248 ?e1 ;
		wdt:P2325 ?b1 .

}
CLUSTER BY ?t1 ?n1 ?a1 ?e1 ?b1 WITH %s AS ?c
