
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?o1 ;
		wdt:P2248 ?t1 ;
		wdt:P2244 ?s1 ;
		wdt:P2243 ?a1 ;
		wdt:P2213 ?y1 ;
		wdt:P2325 ?l1 ;
		wdt:P4501 ?i1 .

}
CLUSTER BY ?o1 ?t1 ?s1 ?a1 ?y1 ?l1 ?i1 WITH %s AS ?c
