
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?y1 ;
		wdt:P2248 ?n1 ;
		wdt:P2244 ?i1 ;
		wdt:P2243 ?u1 ;
		wdt:P2213 ?m1 ;
		wdt:P2325 ?b1 .

}
CLUSTER BY ?y1 ?n1 ?i1 ?u1 ?m1 ?b1 WITH %s AS ?c
