
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?r1 ;
		wdt:P2213 ?p1 ;
		wdt:P2248 ?z1 .

}
CLUSTER BY ?r1 ?p1 ?z1 WITH %s AS ?c
