
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?o1 ;
		wdt:P1457 ?e1 ;
		wdt:P4501 ?c1 ;
		wdt:P2244 ?q1 ;
		wdt:P2213 ?i1 ;
		wdt:P1096 ?g1 ;
		wdt:P2233 ?a1 .

}
CLUSTER BY ?o1 ?e1 ?c1 ?q1 ?i1 ?g1 ?a1 WITH %s AS ?c
