
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2248 ?c1 ;
		wdt:P2213 ?n1 ;
		wdt:P2045 ?a1 ;
		wdt:P1096 ?m1 ;
		wdt:P2325 ?x1 ;
		wdt:P4501 ?l1 .

}
CLUSTER BY ?c1 ?n1 ?a1 ?m1 ?x1 ?l1 WITH %s AS ?c
