
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?r1 ;
		wdt:P4501 ?f1 ;
		wdt:P2244 ?z1 ;
		wdt:P2243 ?p1 ;
		wdt:P2213 ?t1 ;
		wdt:P2325 ?v1 ;
		wdt:P2248 ?o1 .

}
CLUSTER BY ?r1 ?f1 ?z1 ?p1 ?t1 ?v1 ?o1 WITH %s AS ?c
