
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2244 ?m1 ;
		wdt:P1457 ?t1 ;
		wdt:P2213 ?n1 ;
		wdt:P4501 ?b1 ;
		wdt:P2045 ?r1 .

}
CLUSTER BY ?m1 ?t1 ?n1 ?b1 ?r1 WITH %s AS ?c
