
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?j1 ;
		wdt:P1457 ?u1 ;
		wdt:P2248 ?q1 ;
		wdt:P2244 ?a1 ;
		wdt:P2243 ?k1 ;
		wdt:P2213 ?z1 ;
		wdt:P2325 ?e1 ;
		wdt:P4501 ?g1 .

}
CLUSTER BY ?j1 ?u1 ?q1 ?a1 ?k1 ?z1 ?e1 ?g1 WITH %s AS ?c
