
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2154 ?p1 ;
		wdt:P1122 ?w1 ;
		wdt:P2160 ?c1 ;
		wdt:P1086 ?h1 ;
		wdt:P1123 ?l1 ;
		wdt:P1148 ?r1 .

}
CLUSTER BY ?p1 ?w1 ?c1 ?h1 ?l1 ?r1 WITH %s AS ?c
