
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?z1 ;
		wdt:P1457 ?f1 ;
		wdt:P4501 ?q1 ;
		wdt:P2244 ?s1 ;
		wdt:P2243 ?t1 ;
		wdt:P2213 ?d1 ;
		wdt:P2045 ?c1 ;
		wdt:P2325 ?v1 .

}
CLUSTER BY ?z1 ?f1 ?q1 ?s1 ?t1 ?d1 ?c1 ?v1 WITH %s AS ?c
