
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?x1 ;
		wdt:P1457 ?c1 ;
		wdt:P2248 ?d1 ;
		wdt:P2243 ?s1 ;
		wdt:P1096 ?n1 ;
		wdt:P2325 ?e1 ;
		wdt:P2233 ?p1 .

}
CLUSTER BY ?x1 ?c1 ?d1 ?s1 ?n1 ?e1 ?p1 WITH %s AS ?c
