
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?c1 ;
		wdt:P4501 ?h1 ;
		wdt:P2244 ?q1 ;
		wdt:P2213 ?g1 ;
		wdt:P2325 ?d1 ;
		wdt:P2233 ?z1 ;
		wdt:P2248 ?f1 .

}
CLUSTER BY ?c1 ?h1 ?q1 ?g1 ?d1 ?z1 ?f1 WITH %s AS ?c
