
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?s1 ;
		wdt:P2045 ?j1 ;
		wdt:P2233 ?r1 ;
		wdt:P2243 ?o1 .

}
CLUSTER BY ?s1 ?j1 ?r1 ?o1 WITH %s AS ?c
