
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?v1 ;
		wdt:P1457 ?d1 ;
		wdt:P2248 ?t1 ;
		wdt:P2244 ?p1 ;
		wdt:P2243 ?y1 ;
		wdt:P2213 ?q1 ;
		wdt:P2045 ?b1 ;
		wdt:P1096 ?u1 ;
		wdt:P2233 ?r1 .

}
CLUSTER BY ?v1 ?d1 ?t1 ?p1 ?y1 ?q1 ?b1 ?u1 ?r1 WITH %s AS ?c
