
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?b1 ;
		wdt:P2248 ?v1 ;
		wdt:P2244 ?o1 ;
		wdt:P2243 ?c1 ;
		wdt:P2213 ?d1 ;
		wdt:P2045 ?x1 ;
		wdt:P2325 ?t1 ;
		wdt:P2233 ?s1 ;
		wdt:P4501 ?n1 .

}
CLUSTER BY ?b1 ?v1 ?o1 ?c1 ?d1 ?x1 ?t1 ?s1 ?n1 WITH %s AS ?c
