
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2244 ?y1 ;
		wdt:P2045 ?n1 ;
		wdt:P1096 ?x1 ;
		wdt:P2233 ?b1 ;
		wdt:P2243 ?g1 .

}
CLUSTER BY ?y1 ?n1 ?x1 ?b1 ?g1 WITH %s AS ?c
