
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2213 ?u1 ;
		wdt:P1457 ?g1 ;
		wdt:P2233 ?b1 ;
		wdt:P2045 ?l1 ;
		wdt:P2325 ?e1 .

}
CLUSTER BY ?u1 ?g1 ?b1 ?l1 ?e1 WITH %s AS ?c
