
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?u1 ;
		wdt:P2248 ?w1 ;
		wdt:P2244 ?c1 ;
		wdt:P2243 ?i1 ;
		wdt:P2045 ?v1 ;
		wdt:P1096 ?p1 ;
		wdt:P2325 ?k1 ;
		wdt:P2233 ?a1 ;
		wdt:P4501 ?q1 .

}
CLUSTER BY ?u1 ?w1 ?c1 ?i1 ?v1 ?p1 ?k1 ?a1 ?q1 WITH %s AS ?c
