
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2154 ?l1 ;
		wdt:P1122 ?i1 ;
		wdt:P2114 ?w1 .

}
CLUSTER BY ?l1 ?i1 ?w1 WITH %s AS ?c
