
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2244 ?h1 ;
		wdt:P1096 ?y1 ;
		wdt:P2248 ?a1 ;
		wdt:P4501 ?i1 .

}
CLUSTER BY ?h1 ?y1 ?a1 ?i1 WITH %s AS ?c
