
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?x1 ;
		wdt:P2248 ?z1 ;
		wdt:P2243 ?s1 ;
		wdt:P2045 ?e1 ;
		wdt:P1096 ?h1 ;
		wdt:P4501 ?v1 .

}
CLUSTER BY ?x1 ?z1 ?s1 ?e1 ?h1 ?v1 WITH %s AS ?c
