
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?i1 ;
		wdt:P1096 ?s1 ;
		wdt:P2233 ?f1 ;
		wdt:P4501 ?l1 ;
		wdt:P2325 ?e1 .

}
CLUSTER BY ?i1 ?s1 ?f1 ?l1 ?e1 WITH %s AS ?c
