
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?s1 ;
		wdt:P1457 ?z1 ;
		wdt:P2248 ?c1 ;
		wdt:P2244 ?m1 ;
		wdt:P2213 ?o1 ;
		wdt:P2045 ?r1 ;
		wdt:P1096 ?q1 .

}
CLUSTER BY ?s1 ?z1 ?c1 ?m1 ?o1 ?r1 ?q1 WITH %s AS ?c
