
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2045 ?n1 ;
		wdt:P2233 ?y1 ;
		wdt:P2248 ?o1 ;
		wdt:P4501 ?c1 .

}
CLUSTER BY ?n1 ?y1 ?o1 ?c1 WITH %s AS ?c
