
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2325 ?u1 ;
		wdt:P2233 ?a1 ;
		wdt:P2248 ?p1 ;
		wdt:P4501 ?c1 .

}
CLUSTER BY ?u1 ?a1 ?p1 ?c1 WITH %s AS ?c
