
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?b1 ;
		wdt:P2213 ?u1 ;
		wdt:P1457 ?j1 ;
		wdt:P2233 ?q1 ;
		wdt:P2045 ?o1 .

}
CLUSTER BY ?b1 ?u1 ?j1 ?q1 ?o1 WITH %s AS ?c
