
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P4501 ?t1 ;
		wdt:P2244 ?a1 ;
		wdt:P2213 ?k1 ;
		wdt:P2045 ?g1 ;
		wdt:P1096 ?j1 ;
		wdt:P2325 ?z1 .

}
CLUSTER BY ?t1 ?a1 ?k1 ?g1 ?j1 ?z1 WITH %s AS ?c
