
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?y1 ;
		wdt:P2244 ?k1 ;
		wdt:P2325 ?n1 ;
		wdt:P2248 ?l1 ;
		wdt:P4501 ?o1 .

}
CLUSTER BY ?y1 ?k1 ?n1 ?l1 ?o1 WITH %s AS ?c
