
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P4501 ?k1 ;
		wdt:P2244 ?s1 ;
		wdt:P2243 ?d1 ;
		wdt:P2213 ?y1 ;
		wdt:P2045 ?x1 ;
		wdt:P2233 ?e1 .

}
CLUSTER BY ?k1 ?s1 ?d1 ?y1 ?x1 ?e1 WITH %s AS ?c
