
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?z1 ;
		wdt:P2244 ?s1 ;
		wdt:P2243 ?e1 ;
		wdt:P2045 ?y1 ;
		wdt:P1096 ?q1 ;
		wdt:P2325 ?f1 ;
		wdt:P2233 ?v1 .

}
CLUSTER BY ?z1 ?s1 ?e1 ?y1 ?q1 ?f1 ?v1 WITH %s AS ?c
