
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?z1 ;
		wdt:P1457 ?q1 ;
		wdt:P2248 ?a1 ;
		wdt:P2244 ?k1 ;
		wdt:P2243 ?p1 ;
		wdt:P2213 ?c1 ;
		wdt:P2045 ?h1 ;
		wdt:P1096 ?g1 .

}
CLUSTER BY ?z1 ?q1 ?a1 ?k1 ?p1 ?c1 ?h1 ?g1 WITH %s AS ?c
