
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?e1 ;
		wdt:P2244 ?u1 ;
		wdt:P1096 ?b1 ;
		wdt:P2243 ?i1 ;
		wdt:P2213 ?t1 .

}
CLUSTER BY ?e1 ?u1 ?b1 ?i1 ?t1 WITH %s AS ?c
