
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?c1 ;
		wdt:P2213 ?s1 ;
		wdt:P2045 ?v1 ;
		wdt:P2233 ?i1 ;
		wdt:P4501 ?l1 .

}
CLUSTER BY ?c1 ?s1 ?v1 ?i1 ?l1 WITH %s AS ?c
