
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2244 ?q1 ;
		wdt:P2045 ?n1 ;
		wdt:P2213 ?h1 ;
		wdt:P2248 ?x1 ;
		wdt:P2325 ?m1 .

}
CLUSTER BY ?q1 ?n1 ?h1 ?x1 ?m1 WITH %s AS ?c
