
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2213 ?v1 ;
		wdt:P2233 ?z1 ;
		wdt:P2243 ?w1 ;
		wdt:P2325 ?a1 .

}
CLUSTER BY ?v1 ?z1 ?w1 ?a1 WITH %s AS ?c
