
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?r1 ;
		wdt:P1457 ?u1 ;
		wdt:P4501 ?y1 ;
		wdt:P2244 ?b1 ;
		wdt:P2243 ?v1 ;
		wdt:P2213 ?n1 ;
		wdt:P2325 ?z1 ;
		wdt:P2233 ?g1 .

}
CLUSTER BY ?r1 ?u1 ?y1 ?b1 ?v1 ?n1 ?z1 ?g1 WITH %s AS ?c
