
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1086 ?x1 ;
		wdt:P1122 ?h1 ;
		wdt:P2160 ?t1 ;
		wdt:P2114 ?o1 .

}
CLUSTER BY ?x1 ?h1 ?t1 ?o1 WITH %s AS ?c
