
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?t1 ;
		wdt:P1457 ?b1 ;
		wdt:P2248 ?k1 ;
		wdt:P2243 ?w1 ;
		wdt:P2213 ?l1 ;
		wdt:P2045 ?c1 ;
		wdt:P1096 ?o1 ;
		wdt:P2325 ?h1 ;
		wdt:P2233 ?a1 ;
		wdt:P4501 ?r1 .

}
CLUSTER BY ?t1 ?b1 ?k1 ?w1 ?l1 ?c1 ?o1 ?h1 ?a1 ?r1 WITH %s AS ?c
