
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?b1 ;
		wdt:P4501 ?y1 ;
		wdt:P2243 ?o1 ;
		wdt:P2213 ?h1 ;
		wdt:P1096 ?n1 ;
		wdt:P2248 ?p1 .

}
CLUSTER BY ?b1 ?y1 ?o1 ?h1 ?n1 ?p1 WITH %s AS ?c
