
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?n1 ;
		wdt:P1457 ?d1 ;
		wdt:P2233 ?y1 ;
		wdt:P4501 ?l1 ;
		wdt:P2325 ?b1 .

}
CLUSTER BY ?n1 ?d1 ?y1 ?l1 ?b1 WITH %s AS ?c
