
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?f1 ;
		wdt:P2244 ?q1 ;
		wdt:P1457 ?v1 ;
		wdt:P2213 ?e1 ;
		wdt:P2325 ?x1 .

}
CLUSTER BY ?f1 ?q1 ?v1 ?e1 ?x1 WITH %s AS ?c
