
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1123 ?p1 ;
		wdt:P1148 ?h1 ;
		wdt:P2114 ?a1 .

}
CLUSTER BY ?p1 ?h1 ?a1 WITH %s AS ?c
