
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?h1 ;
		wdt:P1457 ?n1 ;
		wdt:P2248 ?i1 ;
		wdt:P2244 ?z1 ;
		wdt:P2045 ?y1 ;
		wdt:P2233 ?e1 ;
		wdt:P4501 ?a1 .

}
CLUSTER BY ?h1 ?n1 ?i1 ?z1 ?y1 ?e1 ?a1 WITH %s AS ?c
