
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?s1 ;
		wdt:P2213 ?j1 ;
		wdt:P2045 ?o1 ;
		wdt:P1096 ?p1 ;
		wdt:P2325 ?u1 ;
		wdt:P2233 ?r1 .

}
CLUSTER BY ?s1 ?j1 ?o1 ?p1 ?u1 ?r1 WITH %s AS ?c
