
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?o1 ;
		wdt:P2244 ?y1 ;
		wdt:P1457 ?b1 ;
		wdt:P4501 ?s1 ;
		wdt:P2213 ?h1 .

}
CLUSTER BY ?o1 ?y1 ?b1 ?s1 ?h1 WITH %s AS ?c
