
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?e1 ;
		wdt:P2244 ?i1 ;
		wdt:P2233 ?s1 ;
		wdt:P2248 ?p1 ;
		wdt:P2213 ?k1 .

}
CLUSTER BY ?e1 ?i1 ?s1 ?p1 ?k1 WITH %s AS ?c
