
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?d1 ;
		wdt:P2248 ?s1 ;
		wdt:P2045 ?a1 ;
		wdt:P1096 ?j1 ;
		wdt:P2325 ?e1 ;
		wdt:P2233 ?z1 .

}
CLUSTER BY ?d1 ?s1 ?a1 ?j1 ?e1 ?z1 WITH %s AS ?c
