
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?g1 ;
		wdt:P4501 ?k1 ;
		wdt:P2243 ?m1 ;
		wdt:P2213 ?e1 ;
		wdt:P1096 ?v1 ;
		wdt:P2325 ?l1 ;
		wdt:P2233 ?a1 ;
		wdt:P2248 ?j1 .

}
CLUSTER BY ?g1 ?k1 ?m1 ?e1 ?v1 ?l1 ?a1 ?j1 WITH %s AS ?c
