
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?e1 ;
		wdt:P2248 ?u1 ;
		wdt:P2045 ?z1 ;
		wdt:P1096 ?v1 ;
		wdt:P2233 ?h1 ;
		wdt:P4501 ?n1 .

}
CLUSTER BY ?e1 ?u1 ?z1 ?v1 ?h1 ?n1 WITH %s AS ?c
