
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2213 ?s1 ;
		wdt:P1457 ?v1 ;
		wdt:P1096 ?b1 ;
		wdt:P2233 ?g1 ;
		wdt:P2243 ?i1 .

}
CLUSTER BY ?s1 ?v1 ?b1 ?g1 ?i1 WITH %s AS ?c
