
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1148 ?u1 ;
		wdt:P2160 ?w1 ;
		wdt:P2114 ?r1 .

}
CLUSTER BY ?u1 ?w1 ?r1 WITH %s AS ?c
