
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2045 ?y1 ;
		wdt:P2233 ?c1 ;
		wdt:P2248 ?s1 ;
		wdt:P2243 ?u1 ;
		wdt:P2325 ?n1 .

}
CLUSTER BY ?y1 ?c1 ?s1 ?u1 ?n1 WITH %s AS ?c
