
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2244 ?n1 ;
		wdt:P1457 ?e1 ;
		wdt:P4501 ?v1 ;
		wdt:P2243 ?g1 ;
		wdt:P2248 ?a1 .

}
CLUSTER BY ?n1 ?e1 ?v1 ?g1 ?a1 WITH %s AS ?c
