
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?f1 ;
		wdt:P1457 ?n1 ;
		wdt:P2244 ?s1 ;
		wdt:P2243 ?c1 ;
		wdt:P2045 ?e1 ;
		wdt:P1096 ?m1 ;
		wdt:P2325 ?v1 ;
		wdt:P2233 ?u1 .

}
CLUSTER BY ?f1 ?n1 ?s1 ?c1 ?e1 ?m1 ?v1 ?u1 WITH %s AS ?c
