
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2248 ?b1 ;
		wdt:P2244 ?l1 ;
		wdt:P2243 ?h1 ;
		wdt:P2045 ?v1 ;
		wdt:P1096 ?n1 ;
		wdt:P2325 ?e1 ;
		wdt:P2233 ?y1 ;
		wdt:P4501 ?x1 .

}
CLUSTER BY ?b1 ?l1 ?h1 ?v1 ?n1 ?e1 ?y1 ?x1 WITH %s AS ?c
