
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?w1 ;
		wdt:P4501 ?y1 ;
		wdt:P2243 ?p1 ;
		wdt:P2213 ?c1 ;
		wdt:P2325 ?r1 ;
		wdt:P2233 ?i1 ;
		wdt:P2248 ?l1 .

}
CLUSTER BY ?w1 ?y1 ?p1 ?c1 ?r1 ?i1 ?l1 WITH %s AS ?c
