
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2213 ?n1 ;
		wdt:P1457 ?r1 ;
		wdt:P4501 ?o1 ;
		wdt:P2243 ?h1 ;
		wdt:P2045 ?e1 .

}
CLUSTER BY ?n1 ?r1 ?o1 ?h1 ?e1 WITH %s AS ?c
