
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?d1 ;
		wdt:P2248 ?n1 ;
		wdt:P2244 ?q1 ;
		wdt:P2045 ?w1 ;
		wdt:P1096 ?v1 ;
		wdt:P2233 ?p1 ;
		wdt:P4501 ?h1 .

}
CLUSTER BY ?d1 ?n1 ?q1 ?w1 ?v1 ?p1 ?h1 WITH %s AS ?c
