
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?v1 ;
		wdt:P1457 ?w1 ;
		wdt:P4501 ?b1 ;
		wdt:P2213 ?z1 ;
		wdt:P1096 ?c1 ;
		wdt:P2325 ?i1 ;
		wdt:P2233 ?k1 .

}
CLUSTER BY ?v1 ?w1 ?b1 ?z1 ?c1 ?i1 ?k1 WITH %s AS ?c
