
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P1457 ?t1 ;
		wdt:P2248 ?b1 ;
		wdt:P2244 ?r1 ;
		wdt:P2045 ?f1 ;
		wdt:P1096 ?d1 ;
		wdt:P2233 ?j1 .

}
CLUSTER BY ?t1 ?b1 ?r1 ?f1 ?d1 ?j1 WITH %s AS ?c
