
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P4501 ?a1 ;
		wdt:P1096 ?o1 ;
		wdt:P2248 ?j1 ;
		wdt:P2243 ?m1 ;
		wdt:P2325 ?t1 .

}
CLUSTER BY ?a1 ?o1 ?j1 ?m1 ?t1 WITH %s AS ?c
