
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?r1 ;
		wdt:P1457 ?e1 ;
		wdt:P2244 ?n1 ;
		wdt:P2243 ?i1 ;
		wdt:P2325 ?l1 ;
		wdt:P2233 ?c1 .

}
CLUSTER BY ?r1 ?e1 ?n1 ?i1 ?l1 ?c1 WITH %s AS ?c
