
PREFIX sim:<http://sj.dcc.uchile.cl/sim#>
PREFIX wdt:<http://www.wikidata.org/prop/direct/>
SELECT * WHERE {
	?id1 wdt:P2146 ?o1 ;
		wdt:P2045 ?n1 ;
		wdt:P1096 ?g1 ;
		wdt:P2243 ?b1 ;
		wdt:P2325 ?c1 .

}
CLUSTER BY ?o1 ?n1 ?g1 ?b1 ?c1 WITH %s AS ?c
