
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ?var12 ?var13 ?var14 ?var15 WHERE  { SELECT DISTINCT ?var11 ?var12 ?var13 (COUNT(?var16) AS ?var15)   WHERE    { SELECT DISTINCT ?var11 ?var12 ?var13 ?var16 (COUNT(?var17) AS ?var14)     WHERE      { ?var11 <http://www.wikidata.org/prop/P166> ?var16 .       ?var16 <http://www.wikidata.org/prop/statement/P166> ?var12 ;          <http://www.wikidata.org/prop/qualifier/P1706> ?var17 ;          <http://www.wikidata.org/prop/qualifier/P585> ?var13 .       ?var12 <http://www.wikidata.org/prop/P31> ?var18 .       ?var18 <http://www.wikidata.org/prop/statement/P31> <http://www.wikidata.org/entity/Q7191>      }     GROUP BY ?var11 ?var12 ?var13 ?var16     HAVING ( ?var14 > 1 )    }   GROUP BY ?var11 ?var12 ?var13 ?var14   HAVING ( COUNT(?var16) > 1 )  }  }
SIMILARITY JOIN ON ( ?var15 ) ( ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ?var22 ?var23 ?var24 ?var25 WHERE  { SELECT DISTINCT ?var21 ?var22 ?var23 (COUNT(?var26) AS ?var25)   WHERE    { SELECT DISTINCT ?var21 ?var22 ?var23 ?var26 (COUNT(?var27) AS ?var24)     WHERE      { ?var21 <http://www.wikidata.org/prop/P166> ?var26 .       ?var26 <http://www.wikidata.org/prop/statement/P166> ?var22 ;          <http://www.wikidata.org/prop/qualifier/P1706> ?var27 ;          <http://www.wikidata.org/prop/qualifier/P585> ?var23 .       ?var22 <http://www.wikidata.org/prop/P31> ?var28 .       ?var28 <http://www.wikidata.org/prop/statement/P31> <http://www.wikidata.org/entity/Q7191>      }     GROUP BY ?var21 ?var22 ?var23 ?var26     HAVING ( ?var24 > 1 )    }   GROUP BY ?var21 ?var22 ?var23 ?var24   HAVING ( COUNT(?var26) > 1 )  }  }
}
