
SELECT * WHERE {
{ SELECT DISTINCT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { ?var12 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424> ;      <http://www.wikidata.org/prop/direct/P57> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { ?var22 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424> ;      <http://www.wikidata.org/prop/direct/P57> ?var21  } GROUP BY ?var21  }
}
