
SELECT * WHERE {
{ SELECT ?var11 (SUM(?var12) AS ?var13) WHERE  { BIND(( ?var14 - ?var15 ) AS ?var12)   ?var11 <http://www.wikidata.org/prop/P39> _:b0 .   _:b0  <http://www.wikidata.org/prop/statement/P39> <http://www.wikidata.org/entity/Q687075> ;      <http://www.wikidata.org/prop/qualifier/P580> ?var15 ;      <http://www.wikidata.org/prop/qualifier/P582> ?var14  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (SUM(?var22) AS ?var23) WHERE  { BIND(( ?var24 - ?var25 ) AS ?var22)   ?var21 <http://www.wikidata.org/prop/P39> _:b0 .   _:b0  <http://www.wikidata.org/prop/statement/P39> <http://www.wikidata.org/entity/Q687075> ;      <http://www.wikidata.org/prop/qualifier/P580> ?var25 ;      <http://www.wikidata.org/prop/qualifier/P582> ?var24  } GROUP BY ?var21  }
}
