
SELECT * WHERE {
{ SELECT (COUNT(?var11) AS ?var12) ?var13 WHERE  { BIND(month(?var14) AS ?var13)   ?var11 <http://www.wikidata.org/prop/direct/P39> <http://www.wikidata.org/entity/Q35494253> ;      <http://www.wikidata.org/prop/direct/P569> ?var14  } GROUP BY ?var13  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT (COUNT(?var21) AS ?var22) ?var23 WHERE  { BIND(month(?var24) AS ?var23)   ?var21 <http://www.wikidata.org/prop/direct/P39> <http://www.wikidata.org/entity/Q35494253> ;      <http://www.wikidata.org/prop/direct/P569> ?var24  } GROUP BY ?var23  }
}
