
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var14  ?var11  ?var12 .   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q247073> .   ?var14  <http://www.wikidata.org/prop/direct/P131>  ?var15 .   ?var14  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .  FILTER (  ( !( isIRI (  ?var12  ) ) )  ) . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var24  ?var21  ?var22 .   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q247073> .   ?var24  <http://www.wikidata.org/prop/direct/P131>  ?var25 .   ?var24  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .  FILTER (  ( !( isIRI (  ?var22  ) ) )  ) . } GROUP BY  ?var21  ?var22   }
}
