
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  WHERE {  {   SELECT ?var11  ?var12 ( COUNT ( ?var12  ) AS  ?var13  )   WHERE   {     ?var15  ?var11  ?var12 .     ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q247073> .     ?var15  <http://www.wikidata.org/prop/direct/P131>  ?var16 .     ?var15  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .  FILTER (    ( !( isIRI (  ?var12  ) ) )  ) .   }   GROUP BY  ?var11  ?var12   }  {   SELECT( COUNT ( DISTINCT  ?var12  ) AS  ?var14  )   WHERE   {     ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q247073> .     ?var15  <http://www.wikidata.org/prop/direct/P131>  ?var16 .     ?var15  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .     ?var15  ?var11  ?var12 .  FILTER (    ( !( isIRI (  ?var12  ) ) )  ) .   }   GROUP BY  ?var11  ?var12   } }  }
SIMILARITY JOIN ON ( ?var13, ?var14 ) ( ?var23, ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  WHERE {  {   SELECT ?var21  ?var22 ( COUNT ( ?var22  ) AS  ?var23  )   WHERE   {     ?var25  ?var21  ?var22 .     ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q247073> .     ?var25  <http://www.wikidata.org/prop/direct/P131>  ?var26 .     ?var25  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .  FILTER (    ( !( isIRI (  ?var22  ) ) )  ) .   }   GROUP BY  ?var21  ?var22   }  {   SELECT( COUNT ( DISTINCT  ?var22  ) AS  ?var24  )   WHERE   {     ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q247073> .     ?var25  <http://www.wikidata.org/prop/direct/P131>  ?var26 .     ?var25  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .     ?var25  ?var21  ?var22 .  FILTER (    ( !( isIRI (  ?var22  ) ) )  ) .   }   GROUP BY  ?var21  ?var22   } }  }
}
