
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> ;      <http://www.wikidata.org/prop/direct/P2054> ?var12 ;      <http://www.wikidata.org/prop/direct/P2054> _:b0 .   _:b0  a           <http://www.wikidata.org/prop/novalue/P2054> ;      <http://www.wikidata.org/prop/qualifier/P2076> ?var13  } LIMIT  100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> ;      <http://www.wikidata.org/prop/direct/P2054> ?var22 ;      <http://www.wikidata.org/prop/direct/P2054> _:b0 .   _:b0  a           <http://www.wikidata.org/prop/novalue/P2054> ;      <http://www.wikidata.org/prop/qualifier/P2076> ?var23  } LIMIT  100  }
}
