
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   BIND (  <http://www.w3.org/2001/XMLSchema#integer>  ( FLOOR (  (  (  NOW (  ) - ?var14  ) /"365.2425"^^<http://www.w3.org/2001/XMLSchema#decimal>  )  ) )  AS  ?var11 ).   ?var12  <http://www.wikidata.org/prop/direct/P569>  ?var14 ;  <http://www.wikidata.org/prop/P39>  [  <http://www.wikidata.org/prop/statement/P39>  <http://www.wikidata.org/entity/Q30524710>  ] . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   BIND (  <http://www.w3.org/2001/XMLSchema#integer>  ( FLOOR (  (  (  NOW (  ) - ?var24  ) /"365.2425"^^<http://www.w3.org/2001/XMLSchema#decimal>  )  ) )  AS  ?var21 ).   ?var22  <http://www.wikidata.org/prop/direct/P569>  ?var24 ;  <http://www.wikidata.org/prop/P39>  [  <http://www.wikidata.org/prop/statement/P39>  <http://www.wikidata.org/entity/Q30524710>  ] . } GROUP BY  ?var21   }
}
