
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P3878>  ?var13 ;  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q101352> ;  <http://www.wikidata.org/prop/direct/P1705>  ?var12 .  FILTER (  (  REGEX (  STR (  ?var12  ) , "string1" )  )  ) . } GROUP BY  ?var11  ?var12   HAVING  ( (  ?var14  = "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P3878>  ?var23 ;  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q101352> ;  <http://www.wikidata.org/prop/direct/P1705>  ?var22 .  FILTER (  (  REGEX (  STR (  ?var22  ) , "string1" )  )  ) . } GROUP BY  ?var21  ?var22   HAVING  ( (  ?var24  = "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
