
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12Label  ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q12136> ;  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12Label . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22Label  ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q12136> ;  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22Label . } GROUP BY  ?var21   }
}
