
SELECT * WHERE {
{ SELECT ?var11 (  SUM ( ?var12  ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q515> .   ?var14  <http://www.wikidata.org/prop/direct/P17>  ?var11 .   ?var14  <http://www.wikidata.org/prop/direct/P1082>  ?var12 . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (  SUM ( ?var22  ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q515> .   ?var24  <http://www.wikidata.org/prop/direct/P17>  ?var21 .   ?var24  <http://www.wikidata.org/prop/direct/P1082>  ?var22 . } GROUP BY  ?var21   }
}
