
SELECT * WHERE {
{ SELECT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { VALUES ?var14 { "12345678" }   ?var12 <http://www.wikidata.org/prop/direct/P698> ?var14 ;      <http://www.wikidata.org/prop/direct/P1433> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { VALUES ?var24 { "12345678" }   ?var22 <http://www.wikidata.org/prop/direct/P698> ?var24 ;      <http://www.wikidata.org/prop/direct/P1433> ?var21  } GROUP BY ?var21  }
}
