
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://wikiba.se/ontology#Property> ;  <http://www.wikidata.org/prop/P2302>  ?var13 .   ?var13  <http://www.wikidata.org/prop/statement/P2302>  ?var12 .  FILTER (  (  ?var12  NOT IN (  <http://www.wikidata.org/entity/Q21502838> , <http://www.wikidata.org/entity/Q21503247> , <http://www.wikidata.org/entity/Q21502404> , <http://www.wikidata.org/entity/Q21510864> , <http://www.wikidata.org/entity/Q21510865> , <http://www.wikidata.org/entity/Q21510856> , <http://www.wikidata.org/entity/Q21503250>  )  )  ) . } GROUP BY  ?var11  ?var12   HAVING  ( (  ?var14  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://wikiba.se/ontology#Property> ;  <http://www.wikidata.org/prop/P2302>  ?var23 .   ?var23  <http://www.wikidata.org/prop/statement/P2302>  ?var22 .  FILTER (  (  ?var22  NOT IN (  <http://www.wikidata.org/entity/Q21502838> , <http://www.wikidata.org/entity/Q21503247> , <http://www.wikidata.org/entity/Q21502404> , <http://www.wikidata.org/entity/Q21510864> , <http://www.wikidata.org/entity/Q21510865> , <http://www.wikidata.org/entity/Q21510856> , <http://www.wikidata.org/entity/Q21503250>  )  )  ) . } GROUP BY  ?var21  ?var22   HAVING  ( (  ?var24  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
