
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { { BIND(year(?var14) AS ?var11)    ?var12 <http://www.wikidata.org/prop/direct/P175> <http://www.wikidata.org/entity/Q255> ;       <http://www.wikidata.org/prop/direct/P571> ?var14   }   FILTER ( ?var11 > 1900 )  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { { BIND(year(?var24) AS ?var21)    ?var22 <http://www.wikidata.org/prop/direct/P175> <http://www.wikidata.org/entity/Q255> ;       <http://www.wikidata.org/prop/direct/P571> ?var24   }   FILTER ( ?var21 > 1900 )  } GROUP BY ?var21  }
}
