
SELECT * WHERE {
{ SELECT DISTINCT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { ?var12 <http://www.wikidata.org/prop/P39> _:b0 .   _:b0  <http://www.wikidata.org/prop/statement/P39> _:b1 ;      <http://www.wikidata.org/prop/qualifier/P4100> ?var14 .   ?var14 <http://www.wikidata.org/prop/direct/P31> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { ?var22 <http://www.wikidata.org/prop/P39> _:b0 .   _:b0  <http://www.wikidata.org/prop/statement/P39> _:b1 ;      <http://www.wikidata.org/prop/qualifier/P4100> ?var24 .   ?var24 <http://www.wikidata.org/prop/direct/P31> ?var21  } GROUP BY ?var21  }
}
