
SELECT * WHERE {
{ SELECT DISTINCT * WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P1539>  ?var12 . } LIMIT 10  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT * WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P1539>  ?var22 . } LIMIT 10  }
}
