
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q577> .   ?var11  <http://www.wikidata.org/prop/direct/P585>  ?var12 .  FILTER (  ( (  YEAR (  ?var12  )  > "1999"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var13  <http://www.wikidata.org/prop/direct/P971>  ?var11 . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q577> .   ?var21  <http://www.wikidata.org/prop/direct/P585>  ?var22 .  FILTER (  ( (  YEAR (  ?var22  )  > "1999"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var23  <http://www.wikidata.org/prop/direct/P971>  ?var21 . } GROUP BY  ?var21  ?var22   }
}
