
SELECT * WHERE {
{ SELECT ?var11Label ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q6256> .   ?var14  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11Label .   ?var14  <http://www.wikidata.org/prop/direct/P47>  ?var12 .  FILTER (  ( (  LANG (  ?var11Label  )  =  "es" ) )  ) . } GROUP BY  ?var11Label   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21Label ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q6256> .   ?var24  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21Label .   ?var24  <http://www.wikidata.org/prop/direct/P47>  ?var22 .  FILTER (  ( (  LANG (  ?var21Label  )  =  "es" ) )  ) . } GROUP BY  ?var21Label   }
}
