
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(DISTINCT ?var13) AS ?var14) WHERE  { ?var13 <http://www.wikidata.org/prop/P50>/<http://www.wikidata.org/prop/statement/P50> <http://www.wikidata.org/entity/Q9358> .   ?var13 <http://www.wikidata.org/prop/P31>/<http://www.wikidata.org/prop/statement/P31> <http://www.wikidata.org/entity/Q571> .   ?var13 ?var11         ?var15 .   ?var12 <http://wikiba.se/ontology#directClaim> ?var11  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(DISTINCT ?var23) AS ?var24) WHERE  { ?var23 <http://www.wikidata.org/prop/P50>/<http://www.wikidata.org/prop/statement/P50> <http://www.wikidata.org/entity/Q9358> .   ?var23 <http://www.wikidata.org/prop/P31>/<http://www.wikidata.org/prop/statement/P31> <http://www.wikidata.org/entity/Q571> .   ?var23 ?var21         ?var25 .   ?var22 <http://wikiba.se/ontology#directClaim> ?var21  } GROUP BY ?var21 ?var22  }
}
