
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(DISTINCT ?var13) AS ?var14) WHERE  { <http://www.wikidata.org/entity/Q489772> <http://www.wikidata.org/prop/P527>/<http://www.wikidata.org/prop/statement/P527> ?var13 .   ?var13 ?var11         ?var15 .   ?var12 <http://wikiba.se/ontology#directClaim> ?var11  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(DISTINCT ?var23) AS ?var24) WHERE  { <http://www.wikidata.org/entity/Q489772> <http://www.wikidata.org/prop/P527>/<http://www.wikidata.org/prop/statement/P527> ?var23 .   ?var23 ?var21         ?var25 .   ?var22 <http://wikiba.se/ontology#directClaim> ?var21  } GROUP BY ?var21 ?var22  }
}
