
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  ?var15  WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var11  <http://www.wikidata.org/prop/direct/P569>  ?var14 .  {   SELECT ?var11 ( COUNT ( ?var16  ) AS  ?var15  )   WHERE   {     ?var11  <http://www.wikidata.org/prop/direct/P569>  ?var14 .   }   GROUP BY  ?var11   }  FILTER (  ( (  ?var15  < "2"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var11  <http://www.wikidata.org/prop/direct/P21>  ?var17 .   ?var17  <http://www.w3.org/2000/01/rdf-schema#label>  ?var13 .   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12 .  FILTER (  ( (  LANG (  ?var13  )  =  "en" ) )  ) .  FILTER (  ( (  LANG (  ?var12  )  =  "en" ) )  ) . }  }
SIMILARITY JOIN ON ( ?var15 ) ( ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  ?var25  WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var21  <http://www.wikidata.org/prop/direct/P569>  ?var24 .  {   SELECT ?var21 ( COUNT ( ?var26  ) AS  ?var25  )   WHERE   {     ?var21  <http://www.wikidata.org/prop/direct/P569>  ?var24 .   }   GROUP BY  ?var21   }  FILTER (  ( (  ?var25  < "2"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var21  <http://www.wikidata.org/prop/direct/P21>  ?var27 .   ?var27  <http://www.w3.org/2000/01/rdf-schema#label>  ?var23 .   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22 .  FILTER (  ( (  LANG (  ?var23  )  =  "en" ) )  ) .  FILTER (  ( (  LANG (  ?var22  )  =  "en" ) )  ) . }  }
}
