
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var12 <http://www.wikidata.org/prop/direct/P2180> ?var14 ;      <http://www.wikidata.org/prop/direct/P21> ?var15 .   ?var15 <http://www.w3.org/2000/01/rdf-schema#label> ?var11   FILTER ( lang(?var11) = "en" )  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var22 <http://www.wikidata.org/prop/direct/P2180> ?var24 ;      <http://www.wikidata.org/prop/direct/P21> ?var25 .   ?var25 <http://www.w3.org/2000/01/rdf-schema#label> ?var21   FILTER ( lang(?var21) = "en" )  } GROUP BY ?var21  }
}
