
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 (COUNT(DISTINCT ?var14) AS ?var15) WHERE  { ?var14 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q247073> ;      <http://www.wikidata.org/prop/direct/P131> ?var16 .   ?var16 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q150093> .   ?var14 ?var11         ?var17  } GROUP BY ?var11 ?var12 ?var13  }
SIMILARITY JOIN ON ( ?var15 ) ( ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 (COUNT(DISTINCT ?var24) AS ?var25) WHERE  { ?var24 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q247073> ;      <http://www.wikidata.org/prop/direct/P131> ?var26 .   ?var26 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q150093> .   ?var24 ?var21         ?var27  } GROUP BY ?var21 ?var22 ?var23  }
}
