
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var11  <http://schema.org/dateModified>  ?var14 .  FILTER (  ( (  ?var14  >  (  NOW (  ) - "PT10M"^^<http://www.w3.org/2001/XMLSchema#duration>  )  ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var21  <http://schema.org/dateModified>  ?var24 .  FILTER (  ( (  ?var24  >  (  NOW (  ) - "PT10M"^^<http://www.w3.org/2001/XMLSchema#duration>  )  ) )  ) . } GROUP BY  ?var21   }
}
