
SELECT * WHERE {
{ SELECT DISTINCT (count(*) AS ?var11) ?var12 WHERE  { ?var13 <http://www.wikidata.org/prop/P2293> ?var14 .   ?var14 <http://www.wikidata.org/prop/statement/P2293> ?var15 ;      <http://www.wikidata.org/prop/qualifier/P459> ?var12  } GROUP BY ?var12  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT (count(*) AS ?var21) ?var22 WHERE  { ?var23 <http://www.wikidata.org/prop/P2293> ?var24 .   ?var24 <http://www.wikidata.org/prop/statement/P2293> ?var25 ;      <http://www.wikidata.org/prop/qualifier/P459> ?var22  } GROUP BY ?var22  }
}
