
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  ?var15  ?var16  ?var17  ?var18  ?var19  WHERE {   ?var19  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7187> ;  <http://www.wikidata.org/prop/direct/P594>  ?var18 .   ?var17  <http://www.wikidata.org/prop/direct/P3433>  ?var19 ;  <http://www.wikidata.org/prop/direct/P31>  ?var16 ;  <http://www.wikidata.org/prop/direct/P1057>  ?var15 ;  <http://www.wikidata.org/prop/direct/P644>  ?var14 ;  <http://www.wikidata.org/prop/direct/P645>  ?var13 ;  <http://www.wikidata.org/prop/direct/P3354>  ?var12 .   ?var15  <http://www.wikidata.org/prop/direct/P1813>  ?var11 .   ?var16  <http://www.wikidata.org/prop/direct/P2888>  <http://purl.obolibrary.org/obo/SO_0001583> . }  }
SIMILARITY JOIN ON ( ?var13, ?var14 ) ( ?var23, ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  ?var25  ?var26  ?var27  ?var28  ?var29  WHERE {   ?var29  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7187> ;  <http://www.wikidata.org/prop/direct/P594>  ?var28 .   ?var27  <http://www.wikidata.org/prop/direct/P3433>  ?var29 ;  <http://www.wikidata.org/prop/direct/P31>  ?var26 ;  <http://www.wikidata.org/prop/direct/P1057>  ?var25 ;  <http://www.wikidata.org/prop/direct/P644>  ?var24 ;  <http://www.wikidata.org/prop/direct/P645>  ?var23 ;  <http://www.wikidata.org/prop/direct/P3354>  ?var22 .   ?var25  <http://www.wikidata.org/prop/direct/P1813>  ?var21 .   ?var26  <http://www.wikidata.org/prop/direct/P2888>  <http://purl.obolibrary.org/obo/SO_0001583> . }  }
}
