
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  ?var15  ?var16  ?var17  ?var18  ?var19  ?var110  WHERE {   ?var110  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7187> ;  <http://www.wikidata.org/prop/direct/P594>  ?var19 .   ?var18  <http://www.wikidata.org/prop/direct/P3433>  ?var110 ;  <http://www.wikidata.org/prop/direct/P31>  ?var17 ;  <http://www.wikidata.org/prop/direct/P1057>  ?var16 ;  <http://www.wikidata.org/prop/direct/P644>  ?var15 ;  <http://www.wikidata.org/prop/direct/P645>  ?var14 ;  <http://www.wikidata.org/prop/direct/P3331>  ?var13 ;  <http://www.wikidata.org/prop/direct/P3354>  ?var12 .   ?var16  <http://www.wikidata.org/prop/direct/P1813>  ?var11 .   ?var17  <http://www.wikidata.org/prop/direct/P2888>  <http://purl.obolibrary.org/obo/SO_0001583> . }  }
SIMILARITY JOIN ON ( ?var14, ?var15 ) ( ?var24, ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  ?var25  ?var26  ?var27  ?var28  ?var29  ?var210  WHERE {   ?var210  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7187> ;  <http://www.wikidata.org/prop/direct/P594>  ?var29 .   ?var28  <http://www.wikidata.org/prop/direct/P3433>  ?var210 ;  <http://www.wikidata.org/prop/direct/P31>  ?var27 ;  <http://www.wikidata.org/prop/direct/P1057>  ?var26 ;  <http://www.wikidata.org/prop/direct/P644>  ?var25 ;  <http://www.wikidata.org/prop/direct/P645>  ?var24 ;  <http://www.wikidata.org/prop/direct/P3331>  ?var23 ;  <http://www.wikidata.org/prop/direct/P3354>  ?var22 .   ?var26  <http://www.wikidata.org/prop/direct/P1813>  ?var21 .   ?var27  <http://www.wikidata.org/prop/direct/P2888>  <http://purl.obolibrary.org/obo/SO_0001583> . }  }
}
