
SELECT * WHERE {
{ SELECT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { <http://www.wikidata.org/entity/Q815819>        <http://www.wikidata.org/prop/direct/P2176> ?var14 .   ?var11   <http://www.wikidata.org/prop/direct/P2176> ?var14 ;        <http://www.wikidata.org/prop/direct/P2176> ?var12  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { <http://www.wikidata.org/entity/Q815819>        <http://www.wikidata.org/prop/direct/P2176> ?var24 .   ?var21   <http://www.wikidata.org/prop/direct/P2176> ?var24 ;        <http://www.wikidata.org/prop/direct/P2176> ?var22  } GROUP BY ?var21  }
}
