
SELECT * WHERE {
{ SELECT ?var11  ?var12  WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q12136> .   ?var13  <http://www.wikidata.org/prop/direct/P3488>  ?var12 .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var11  )  =  "en" ) )  ) . }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q12136> .   ?var23  <http://www.wikidata.org/prop/direct/P3488>  ?var22 .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var21  )  =  "en" ) )  ) . }  }
}
