
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) ?var14 WHERE  { { BIND(str(year(?var15)) AS ?var11)    ?var12 <http://www.wikidata.org/prop/direct/P1552> ?var14 ;       <http://www.wikidata.org/prop/direct/P577> ?var15   }   VALUES ?var14 { <http://www.wikidata.org/entity/Q45171911> <http://www.wikidata.org/entity/Q45172088> }  } GROUP BY ?var11 ?var14  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) ?var24 WHERE  { { BIND(str(year(?var25)) AS ?var21)    ?var22 <http://www.wikidata.org/prop/direct/P1552> ?var24 ;       <http://www.wikidata.org/prop/direct/P577> ?var25   }   VALUES ?var24 { <http://www.wikidata.org/entity/Q45171911> <http://www.wikidata.org/entity/Q45172088> }  } GROUP BY ?var21 ?var24  }
}
