
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { { ?var12 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q486972> ;       <http://www.wikidata.org/prop/direct/P31> ?var11    MINUS     { ?var11 <http://www.wikidata.org/prop/direct/P17> _:b0 }   }   FILTER ( ?var11 != <http://www.wikidata.org/entity/Q486972> )  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { { ?var22 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q486972> ;       <http://www.wikidata.org/prop/direct/P31> ?var21    MINUS     { ?var21 <http://www.wikidata.org/prop/direct/P17> _:b0 }   }   FILTER ( ?var21 != <http://www.wikidata.org/entity/Q486972> )  } GROUP BY ?var21  }
}
