
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var13  <http://www.wikidata.org/prop/P166>  ?var15 .   ?var15  <http://www.wikidata.org/prop/statement/P166>  <http://www.wikidata.org/entity/Q44585> .   ?var15  <http://www.wikidata.org/prop/qualifier/P585>  ?var16 .   ?var13  <http://www.wikidata.org/prop/direct/P27>  ?var11 . } GROUP BY  ?var11 (  YEAR (  ?var16  )  AS  ?var12  )  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var23  <http://www.wikidata.org/prop/P166>  ?var25 .   ?var25  <http://www.wikidata.org/prop/statement/P166>  <http://www.wikidata.org/entity/Q44585> .   ?var25  <http://www.wikidata.org/prop/qualifier/P585>  ?var26 .   ?var23  <http://www.wikidata.org/prop/direct/P27>  ?var21 . } GROUP BY  ?var21 (  YEAR (  ?var26  )  AS  ?var22  )  }
}
