
SELECT * WHERE {
{ SELECT ?var11 ?var12 (count(*) AS ?var13) WHERE  { ?var14 <http://www.wikidata.org/prop/P166> ?var15 .   ?var15 <http://www.wikidata.org/prop/statement/P166> <http://www.wikidata.org/entity/Q44585> ;      <http://www.wikidata.org/prop/qualifier/P585> ?var16 .   ?var14 <http://www.wikidata.org/prop/direct/P27> ?var11  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (count(*) AS ?var23) WHERE  { ?var24 <http://www.wikidata.org/prop/P166> ?var25 .   ?var25 <http://www.wikidata.org/prop/statement/P166> <http://www.wikidata.org/entity/Q44585> ;      <http://www.wikidata.org/prop/qualifier/P585> ?var26 .   ?var24 <http://www.wikidata.org/prop/direct/P27> ?var21  } GROUP BY ?var21 ?var22  }
}
