
SELECT * WHERE {
{ SELECT DISTINCT ?var11 (COUNT(?var11) AS ?var12) WHERE  { ?var13 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q1914636> .   ?var14 ?var11         ?var13  } GROUP BY ?var11 LIMIT  100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 (COUNT(?var21) AS ?var22) WHERE  { ?var23 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q1914636> .   ?var24 ?var21         ?var23  } GROUP BY ?var21 LIMIT  100  }
}
