
SELECT * WHERE {
{ SELECT ?var11Label  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var16 .   ?var15  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var17 .   ?var13  <http://www.wikidata.org/prop/direct/P69>  ?var15 .   ?var13  <http://www.wikidata.org/prop/direct/P509>  ?var11Label .   ?var11Label  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12 .  FILTER (  ( (  LANG (  ?var16  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var17  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var12  )  =  "es" ) )  ) . } GROUP BY  ?var11Label  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21Label  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var26 .   ?var25  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var27 .   ?var23  <http://www.wikidata.org/prop/direct/P69>  ?var25 .   ?var23  <http://www.wikidata.org/prop/direct/P509>  ?var21Label .   ?var21Label  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22 .  FILTER (  ( (  LANG (  ?var26  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var27  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var22  )  =  "es" ) )  ) . } GROUP BY  ?var21Label  ?var22   }
}
