
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { SELECT ?var11 ?var12 (COUNT(DISTINCT ?var14) AS ?var13)   WHERE    { { { ?var14 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;          <http://www.wikidata.org/prop/direct/P21> ?var12 ;          <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183> .       ?var14 <http://www.wikidata.org/prop/P569>/<http://www.wikidata.org/prop/statement/value/P569> _:b0 .       _:b0 <http://wikiba.se/ontology#timeValue> ?var15 ;          <http://wikiba.se/ontology#timePrecision> ?var16       MINUS        { ?var14 <http://www.wikidata.org/prop/direct/P570> ?var17 }      }      BIND(<http://www.w3.org/2001/XMLSchema#integer>(floor(( ( now() - ?var15 ) / 365.2425 ))) AS ?var11)     }     FILTER ( ?var16 >= 9 )     FILTER ( ?var15 >= "1900-00-00"^^<http://www.w3.org/2001/XMLSchema#dateTime> )    }   GROUP BY ?var11 ?var12  }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { SELECT ?var21 ?var22 (COUNT(DISTINCT ?var24) AS ?var23)   WHERE    { { { ?var24 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;          <http://www.wikidata.org/prop/direct/P21> ?var22 ;          <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183> .       ?var24 <http://www.wikidata.org/prop/P569>/<http://www.wikidata.org/prop/statement/value/P569> _:b0 .       _:b0 <http://wikiba.se/ontology#timeValue> ?var25 ;          <http://wikiba.se/ontology#timePrecision> ?var26       MINUS        { ?var24 <http://www.wikidata.org/prop/direct/P570> ?var27 }      }      BIND(<http://www.w3.org/2001/XMLSchema#integer>(floor(( ( now() - ?var25 ) / 365.2425 ))) AS ?var21)     }     FILTER ( ?var26 >= 9 )     FILTER ( ?var25 >= "1900-00-00"^^<http://www.w3.org/2001/XMLSchema#dateTime> )    }   GROUP BY ?var21 ?var22  }  }
}
