
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { SELECT ?var11 (COUNT(?var13) AS ?var12)   WHERE    { ?var13 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;        <http://www.wikidata.org/prop/direct/P734> ?var11    }   GROUP BY ?var11  } LIMIT  100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { SELECT ?var21 (COUNT(?var23) AS ?var22)   WHERE    { ?var23 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;        <http://www.wikidata.org/prop/direct/P734> ?var21    }   GROUP BY ?var21  } LIMIT  100  }
}
