
SELECT * WHERE {
{ SELECT( COUNT ( ?var11  ) AS  ?var12  ) ?var11  WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var13  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var14  <http://www.wikidata.org/prop/direct/P69>  ?var13 .   ?var14  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11424> .   ?var15  <http://www.wikidata.org/prop/direct/P57>  ?var14 .   ?var15  <http://www.wikidata.org/prop/direct/P577>  ?var16 .   ?var14  <http://www.w3.org/2000/01/rdf-schema#label>  ?var17 .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var18 .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var18  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var17  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT( COUNT ( ?var21  ) AS  ?var22  ) ?var21  WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var23  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var24  <http://www.wikidata.org/prop/direct/P69>  ?var23 .   ?var24  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11424> .   ?var25  <http://www.wikidata.org/prop/direct/P57>  ?var24 .   ?var25  <http://www.wikidata.org/prop/direct/P577>  ?var26 .   ?var24  <http://www.w3.org/2000/01/rdf-schema#label>  ?var27 .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var28 .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var28  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var27  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) )  ) . } GROUP BY  ?var21   }
}
