
SELECT * WHERE {
{ SELECT (COUNT(DISTINCT ?var11) AS ?var12) ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;      <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q483501> ;      <http://www.wikidata.org/prop/direct/P27> ?var13  } GROUP BY ?var13  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT (COUNT(DISTINCT ?var21) AS ?var22) ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;      <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q483501> ;      <http://www.wikidata.org/prop/direct/P27> ?var23  } GROUP BY ?var23  }
}
