
SELECT * WHERE {
{ SELECT ?var11 ( COUNT (* ) AS  ?var12  ) WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14 .   ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var16 .   ?var15  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var13  <http://www.wikidata.org/prop/direct/P69>  ?var15 .   ?var13  <http://www.wikidata.org/prop/direct/P1196>  ?var11 .   ?var17  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var14  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var16  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT (* ) AS  ?var22  ) WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24 .   ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var26 .   ?var25  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var23  <http://www.wikidata.org/prop/direct/P69>  ?var25 .   ?var23  <http://www.wikidata.org/prop/direct/P1196>  ?var21 .   ?var27  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var24  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var26  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) )  ) . } GROUP BY  ?var21   }
}
