
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  WHERE {  FILTER (  ( (  ?var12  = "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .  FILTER (  ( (  ?var13  < "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var11  <http://wikiba.se/ontology#statements>  ?var13 .  {   SELECT ?var11 ( COUNT ( ?var15  ) AS  ?var12  )   WHERE   {     ?var14  <http://schema.org/about>  ?var11 .     ?var14  <http://schema.org/isPartOf>  <https://cs.wikipedia.org/> .     ?var15  <http://schema.org/about>  ?var11 .   }   GROUP BY  ?var11   } } LIMIT 100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  WHERE {  FILTER (  ( (  ?var22  = "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .  FILTER (  ( (  ?var23  < "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var21  <http://wikiba.se/ontology#statements>  ?var23 .  {   SELECT ?var21 ( COUNT ( ?var25  ) AS  ?var22  )   WHERE   {     ?var24  <http://schema.org/about>  ?var21 .     ?var24  <http://schema.org/isPartOf>  <https://cs.wikipedia.org/> .     ?var25  <http://schema.org/about>  ?var21 .   }   GROUP BY  ?var21   } } LIMIT 100  }
}
