
SELECT * WHERE {
{ SELECT ?var11 ( COUNT (* ) AS  ?var12  ) WHERE {   <http://www.wikidata.org/entity/Q9197118>  ?var11  ?var13 .  FILTER (  (  isLITERAL (  ?var13  )  )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT (* ) AS  ?var22  ) WHERE {   <http://www.wikidata.org/entity/Q9197118>  ?var21  ?var23 .  FILTER (  (  isLITERAL (  ?var23  )  )  ) . } GROUP BY  ?var21   }
}
