
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(DISTINCT ?var13) AS ?var14) WHERE  { { BIND(year(?var15) AS ?var12)    ?var13 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q215380> ;       <http://www.wikidata.org/prop/direct/P571> ?var15 ;       <http://www.wikidata.org/prop/direct/P136> ?var11   }   FILTER ( ?var15 > "1900-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(DISTINCT ?var23) AS ?var24) WHERE  { { BIND(year(?var25) AS ?var22)    ?var23 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q215380> ;       <http://www.wikidata.org/prop/direct/P571> ?var25 ;       <http://www.wikidata.org/prop/direct/P136> ?var21   }   FILTER ( ?var25 > "1900-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var21 ?var22  }
}
