
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13Label (COUNT(DISTINCT ?var14) AS ?var15) WHERE  { { BIND(year(?var16) AS ?var12)    ?var14 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q215380> ;       <http://www.wikidata.org/prop/direct/P571> ?var16 ;       <http://www.wikidata.org/prop/direct/P136> ?var11 ;       <http://www.wikidata.org/prop/direct/P740> ?var13Label   }   FILTER ( ?var16 > "1900-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var11 ?var12 ?var13Label  }
SIMILARITY JOIN ON ( ?var15 ) ( ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23Label (COUNT(DISTINCT ?var24) AS ?var25) WHERE  { { BIND(year(?var26) AS ?var22)    ?var24 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q215380> ;       <http://www.wikidata.org/prop/direct/P571> ?var26 ;       <http://www.wikidata.org/prop/direct/P136> ?var21 ;       <http://www.wikidata.org/prop/direct/P740> ?var23Label   }   FILTER ( ?var26 > "1900-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var21 ?var22 ?var23Label  }
}
