
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) WHERE  { ?var13 <http://www.wikidata.org/prop/direct/P1340> ?var15 ;      <http://www.wikidata.org/prop/direct/P1884> ?var12 ;      <http://www.wikidata.org/prop/direct/P2048> ?var16   BIND(concat(?var17Label, " eyes") AS ?var11)  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) WHERE  { ?var23 <http://www.wikidata.org/prop/direct/P1340> ?var25 ;      <http://www.wikidata.org/prop/direct/P1884> ?var22 ;      <http://www.wikidata.org/prop/direct/P2048> ?var26   BIND(concat(?var27Label, " eyes") AS ?var21)  } GROUP BY ?var21 ?var22  }
}
