
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 ?var14 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q6256> ;      <http://www.wikidata.org/prop/direct/P1082> ?var12 ;      <http://www.wikidata.org/prop/direct/P2131> ?var13 ;      <http://www.wikidata.org/prop/direct/P361> ?var14    {  {  {  {  { ?var11 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q48> }           UNION            { ?var11 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q46> }          }         UNION          { ?var11 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q49> }        }       UNION        { ?var11 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q18> }      }     UNION      { ?var11 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q15> }    }   UNION    { ?var11 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q46> }  }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 ?var24 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q6256> ;      <http://www.wikidata.org/prop/direct/P1082> ?var22 ;      <http://www.wikidata.org/prop/direct/P2131> ?var23 ;      <http://www.wikidata.org/prop/direct/P361> ?var24    {  {  {  {  { ?var21 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q48> }           UNION            { ?var21 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q46> }          }         UNION          { ?var21 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q49> }        }       UNION        { ?var21 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q18> }      }     UNION      { ?var21 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q15> }    }   UNION    { ?var21 <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q46> }  }  }
}
