
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var12) AS ?var13) WHERE  { ?var14 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;      <http://www.wikidata.org/prop/direct/P27> ?var11 ;      <http://www.wikidata.org/prop/direct/P166> ?var12 .   ?var12 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q7191>  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var22) AS ?var23) WHERE  { ?var24 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;      <http://www.wikidata.org/prop/direct/P27> ?var21 ;      <http://www.wikidata.org/prop/direct/P166> ?var22 .   ?var22 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q7191>  } GROUP BY ?var21 ?var22  }
}
