
SELECT * WHERE {
{ SELECT ?var11 ?var12 (count(*) AS ?var13) WHERE  { ?var14 <http://www.wikidata.org/prop/direct/P27> ?var11 .   ?var11 <http://www.wikidata.org/prop/direct/P30> <http://www.wikidata.org/entity/Q46> .   ?var14 <http://www.wikidata.org/prop/direct/P26> ?var15 .   ?var15 <http://www.wikidata.org/prop/direct/P27> ?var12 .   ?var12 <http://www.wikidata.org/prop/direct/P30> <http://www.wikidata.org/entity/Q46>   FILTER ( <http://www.wikidata.org/entity/Q3024240> IN (?var11, ?var12) )   FILTER ( ?var11 != ?var12 )  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (count(*) AS ?var23) WHERE  { ?var24 <http://www.wikidata.org/prop/direct/P27> ?var21 .   ?var21 <http://www.wikidata.org/prop/direct/P30> <http://www.wikidata.org/entity/Q46> .   ?var24 <http://www.wikidata.org/prop/direct/P26> ?var25 .   ?var25 <http://www.wikidata.org/prop/direct/P27> ?var22 .   ?var22 <http://www.wikidata.org/prop/direct/P30> <http://www.wikidata.org/entity/Q46>   FILTER ( <http://www.wikidata.org/entity/Q3024240> IN (?var21, ?var22) )   FILTER ( ?var21 != ?var22 )  } GROUP BY ?var21 ?var22  }
}
