
SELECT * WHERE {
{ SELECT DISTINCT * WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P527>  ?var12 ,  ?var13 .   ?var12  <http://www.wikidata.org/prop/direct/P1117>  ?var14 .   ?var13  <http://www.wikidata.org/prop/direct/P1117>  ?var15 . }  }
SIMILARITY JOIN ON ( ?var14, ?var15 ) ( ?var24, ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT * WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P527>  ?var22 ,  ?var23 .   ?var22  <http://www.wikidata.org/prop/direct/P1117>  ?var24 .   ?var23  <http://www.wikidata.org/prop/direct/P1117>  ?var25 . }  }
}
