
SELECT * WHERE {
{ SELECT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { BIND(year(?var14) AS ?var15)   ?var12 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q215380> ;      <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q131578> ;      <http://www.wikidata.org/prop/direct/P571> ?var14 ;      <http://www.wikidata.org/prop/direct/P136> ?var16 ;      <http://www.wikidata.org/prop/direct/P740> ?var17 .   ?var17 <http://www.wikidata.org/prop/direct/P17> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { BIND(year(?var24) AS ?var25)   ?var22 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q215380> ;      <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q131578> ;      <http://www.wikidata.org/prop/direct/P571> ?var24 ;      <http://www.wikidata.org/prop/direct/P136> ?var26 ;      <http://www.wikidata.org/prop/direct/P740> ?var27 .   ?var27 <http://www.wikidata.org/prop/direct/P17> ?var21  } GROUP BY ?var21  }
}
