
SELECT * WHERE {
{ SELECT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { { SELECT ?var12 (COUNT(?var12) AS ?var14)    WHERE     { { ?var12 <http://www.wikidata.org/prop/P31> _:b0 .       _:b0  <http://www.wikidata.org/prop/statement/P31> <http://www.wikidata.org/entity/Q7889> .       ?var12 <http://www.wikidata.org/prop/P31> ?var15       MINUS        { ?var12 <http://www.wikidata.org/prop/P577> ?var16 }      }      ?var17 <http://schema.org/about> ?var12 ;         <http://schema.org/inLanguage> ?var11     }    GROUP BY ?var12   }   FILTER ( ?var14 = 1 )  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { { SELECT ?var22 (COUNT(?var22) AS ?var24)    WHERE     { { ?var22 <http://www.wikidata.org/prop/P31> _:b0 .       _:b0  <http://www.wikidata.org/prop/statement/P31> <http://www.wikidata.org/entity/Q7889> .       ?var22 <http://www.wikidata.org/prop/P31> ?var25       MINUS        { ?var22 <http://www.wikidata.org/prop/P577> ?var26 }      }      ?var27 <http://schema.org/about> ?var22 ;         <http://schema.org/inLanguage> ?var21     }    GROUP BY ?var22   }   FILTER ( ?var24 = 1 )  } GROUP BY ?var21  }
}
