
SELECT * WHERE {
{ SELECT ?var11 (AVG(?var12) AS ?var13) WHERE  { { BIND(( year(?var14) - year(?var15) ) AS ?var12)    BIND(year(?var14) AS ?var11)   }   ?var16 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q937857> ;      <http://www.wikidata.org/prop/direct/P569> ?var15 ;      <http://www.wikidata.org/prop/P54> ?var17 .   ?var17 <http://www.wikidata.org/prop/statement/P54> <http://www.wikidata.org/entity/Q47774> ;      <http://www.wikidata.org/prop/qualifier/P580> ?var14  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (AVG(?var22) AS ?var23) WHERE  { { BIND(( year(?var24) - year(?var25) ) AS ?var22)    BIND(year(?var24) AS ?var21)   }   ?var26 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q937857> ;      <http://www.wikidata.org/prop/direct/P569> ?var25 ;      <http://www.wikidata.org/prop/P54> ?var27 .   ?var27 <http://www.wikidata.org/prop/statement/P54> <http://www.wikidata.org/entity/Q47774> ;      <http://www.wikidata.org/prop/qualifier/P580> ?var24  } GROUP BY ?var21  }
}
