
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  WHERE {  {   SELECT DISTINCT ?var12 ( COUNT ( ?var12  ) AS  ?var13  )   WHERE   {     ?var11  <http://www.wikidata.org/prop/direct/P279>  <http://www.wikidata.org/entity/Q7187> ;  <http://www.wikidata.org/prop/direct/P351>  ?var12 .   }   GROUP BY  ?var12  ?var14   }  FILTER (  ( (  ?var13  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  WHERE {  {   SELECT DISTINCT ?var22 ( COUNT ( ?var22  ) AS  ?var23  )   WHERE   {     ?var21  <http://www.wikidata.org/prop/direct/P279>  <http://www.wikidata.org/entity/Q7187> ;  <http://www.wikidata.org/prop/direct/P351>  ?var22 .   }   GROUP BY  ?var22  ?var24   }  FILTER (  ( (  ?var23  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . }  }
}
