
SELECT * WHERE {
{ SELECT ?var11  ?var11Label  ?var12  ?var13  ?var14Label  WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P2573>  ?var12 . }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var21Label  ?var22  ?var23  ?var24Label  WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P2573>  ?var22 . }  }
}
