
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var12  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11424> .   ?var12  <http://www.wikidata.org/prop/direct/P57>  ?var14 .   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var14  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var14  <http://www.wikidata.org/prop/direct/P69>  ?var15 .   ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .   ?var15  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var22  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11424> .   ?var22  <http://www.wikidata.org/prop/direct/P57>  ?var24 .   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var24  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var24  <http://www.wikidata.org/prop/direct/P69>  ?var25 .   ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .   ?var25  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) )  ) . } GROUP BY  ?var21   }
}
