
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { ?var13 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> ;      <http://www.wikidata.org/prop/direct/P246> ?var11 ;      <http://www.wikidata.org/prop/direct/P1086> ?var12  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { ?var23 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> ;      <http://www.wikidata.org/prop/direct/P246> ?var21 ;      <http://www.wikidata.org/prop/direct/P1086> ?var22  }  }
}
