
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT (* ) AS  ?var13  ) WHERE {   VALUES (  ?var11  ) {    (  <http://www.wikidata.org/entity/Q21042795>  )    (  <http://www.wikidata.org/entity/Q21042800>  )    (  <http://www.wikidata.org/entity/Q20950423>  )    (  <http://www.wikidata.org/entity/Q21042799>  )   }   BIND (  REPLACE (  STR (  ?var14Label  ) , "^[^:]+:", "" )  AS  ?var12 ).   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14Label . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT (* ) AS  ?var23  ) WHERE {   VALUES (  ?var21  ) {    (  <http://www.wikidata.org/entity/Q21042795>  )    (  <http://www.wikidata.org/entity/Q21042800>  )    (  <http://www.wikidata.org/entity/Q20950423>  )    (  <http://www.wikidata.org/entity/Q21042799>  )   }   BIND (  REPLACE (  STR (  ?var24Label  ) , "^[^:]+:", "" )  AS  ?var22 ).   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24Label . } GROUP BY  ?var21  ?var22   }
}
