
SELECT * WHERE {
{ SELECT ?var11  ?var12  WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P1088>  ?var12 .  FILTER (  ( (  ?var12  >= "5"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } LIMIT 100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P1088>  ?var22 .  FILTER (  ( (  ?var22  >= "5"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } LIMIT 100  }
}
