
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var11  ) AS  ?var12  ) WHERE {   []  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> ;  <http://www.wikidata.org/prop/direct/P21>  <http://www.wikidata.org/entity/Q6581097> ;  <http://www.wikidata.org/prop/direct/P91>  <http://www.wikidata.org/entity/Q6636> ;  <http://www.wikidata.org/prop/direct/P106>  ?var11 . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var21  ) AS  ?var22  ) WHERE {   []  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> ;  <http://www.wikidata.org/prop/direct/P21>  <http://www.wikidata.org/entity/Q6581097> ;  <http://www.wikidata.org/prop/direct/P91>  <http://www.wikidata.org/entity/Q6636> ;  <http://www.wikidata.org/prop/direct/P106>  ?var21 . } GROUP BY  ?var21   }
}
