
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12 .   ?var16  <http://www.wikidata.org/prop/direct/P69>  ?var15 .   ?var16  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var16  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .   ?var13  <http://www.wikidata.org/prop/direct/P57>  ?var16 .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var12  )  =  "es" ) )  ) . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22 .   ?var26  <http://www.wikidata.org/prop/direct/P69>  ?var25 .   ?var26  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var26  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .   ?var23  <http://www.wikidata.org/prop/direct/P57>  ?var26 .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var22  )  =  "es" ) )  ) . } GROUP BY  ?var21  ?var22   }
}
