
SELECT * WHERE {
{ SELECT DISTINCT (count(*) AS ?var11) ?var12 WHERE  { ?var13 <http://www.wikidata.org/prop/direct/P991> ?var14 .   ?var14 <http://www.wikidata.org/prop/direct/P512> ?var15 ;      <http://www.wikidata.org/prop/direct/P19> ?var16 ;      <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183>  } GROUP BY ?var12  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT (count(*) AS ?var21) ?var22 WHERE  { ?var23 <http://www.wikidata.org/prop/direct/P991> ?var24 .   ?var24 <http://www.wikidata.org/prop/direct/P512> ?var25 ;      <http://www.wikidata.org/prop/direct/P19> ?var26 ;      <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183>  } GROUP BY ?var22  }
}
