
SELECT * WHERE {
{ SELECT ?var11  ?var12  WHERE {  SELECT ?var13 ( COUNT ( ?var14  ) AS  ?var11  )  WHERE  {    BIND (  YEAR (  ?var15  )  AS  ?var13 ).    ?var14  <http://www.wikidata.org/prop/direct/P21>  <http://www.wikidata.org/entity/Q6581097> ;  <http://www.wikidata.org/prop/direct/P27>  <http://www.wikidata.org/entity/Q20> ;  <http://www.wikidata.org/prop/direct/P569>  ?var15 .  }  GROUP BY  ?var13  }  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  WHERE {  SELECT ?var23 ( COUNT ( ?var24  ) AS  ?var21  )  WHERE  {    BIND (  YEAR (  ?var25  )  AS  ?var23 ).    ?var24  <http://www.wikidata.org/prop/direct/P21>  <http://www.wikidata.org/entity/Q6581097> ;  <http://www.wikidata.org/prop/direct/P27>  <http://www.wikidata.org/entity/Q20> ;  <http://www.wikidata.org/prop/direct/P569>  ?var25 .  }  GROUP BY  ?var23  }  }
}
