
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q23397> ;      <http://www.wikidata.org/prop/direct/P4511> ?var13  } LIMIT  10  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q23397> ;      <http://www.wikidata.org/prop/direct/P4511> ?var23  } LIMIT  10  }
}
