
SELECT * WHERE {
{ SELECT DISTINCT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P496> ?var14 ;      <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> .   ?var12 <http://www.wikidata.org/prop/direct/P50> ?var11 .   ?var11 <http://www.wikidata.org/prop/direct/P108> "string1"  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P496> ?var24 ;      <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> .   ?var22 <http://www.wikidata.org/prop/direct/P50> ?var21 .   ?var21 <http://www.wikidata.org/prop/direct/P108> "string1"  } GROUP BY ?var21  }
}
