
SELECT * WHERE {
{ SELECT * WHERE {   <http://www.wikidata.org/entity/Q513>  <http://www.wikidata.org/prop/direct/P2660>  ?var11 .   ?var11  <http://www.wikidata.org/prop/direct/P2048>  ?var12 . }  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT * WHERE {   <http://www.wikidata.org/entity/Q513>  <http://www.wikidata.org/prop/direct/P2660>  ?var21 .   ?var21  <http://www.wikidata.org/prop/direct/P2048>  ?var22 . }  }
}
