
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q1371849> .   ?var14 <http://schema.org/about> ?var11 ;      <http://schema.org/isPartOf> <https://www.wikidata.org/> .   ?var12 <http://www.wikidata.org/prop/direct/P57>|<http://www.wikidata.org/prop/direct/P161> ?var15 .   ?var11 <http://www.wikidata.org/prop/direct/P175> ?var15  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q1371849> .   ?var24 <http://schema.org/about> ?var21 ;      <http://schema.org/isPartOf> <https://www.wikidata.org/> .   ?var22 <http://www.wikidata.org/prop/direct/P57>|<http://www.wikidata.org/prop/direct/P161> ?var25 .   ?var21 <http://www.wikidata.org/prop/direct/P175> ?var25  } GROUP BY ?var21  }
}
