
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5398426> ;      <http://www.wikidata.org/prop/direct/P161> ?var12  } GROUP BY ?var11 LIMIT  1000  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5398426> ;      <http://www.wikidata.org/prop/direct/P161> ?var22  } GROUP BY ?var21 LIMIT  1000  }
}
