
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) ?var15 WHERE  { ?var13 <http://www.wikidata.org/prop/direct/P1340> ?var11 ;      <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q159> ;      <http://www.wikidata.org/prop/direct/P27> ?var15  } GROUP BY ?var11 ?var12 ?var15  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) ?var25 WHERE  { ?var23 <http://www.wikidata.org/prop/direct/P1340> ?var21 ;      <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q159> ;      <http://www.wikidata.org/prop/direct/P27> ?var25  } GROUP BY ?var21 ?var22 ?var25  }
}
