
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( DISTINCT  ?var12  ) AS  ?var13  ) WHERE {   ?var12  <http://schema.org/about>  <http://www.wikidata.org/entity/Q19673> . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( DISTINCT  ?var22  ) AS  ?var23  ) WHERE {   ?var22  <http://schema.org/about>  <http://www.wikidata.org/entity/Q19673> . } GROUP BY  ?var21   }
}
