
SELECT * WHERE {
{ SELECT ?var11 (SUM(?var12) AS ?var13) WHERE  { { VALUES ?var14 { <http://www.wikidata.org/entity/Q587094> <http://www.wikidata.org/entity/Q587094> }    BIND(str(year(?var15)) AS ?var11)   }   ?var14 <http://www.wikidata.org/prop/P1082> ?var16 .   ?var16 <http://www.wikidata.org/prop/statement/P1082> ?var12 ;      <http://www.wikidata.org/prop/qualifier/P585> ?var15  } GROUP BY ?var11 ?var14  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (SUM(?var22) AS ?var23) WHERE  { { VALUES ?var24 { <http://www.wikidata.org/entity/Q587094> <http://www.wikidata.org/entity/Q587094> }    BIND(str(year(?var25)) AS ?var21)   }   ?var24 <http://www.wikidata.org/prop/P1082> ?var26 .   ?var26 <http://www.wikidata.org/prop/statement/P1082> ?var22 ;      <http://www.wikidata.org/prop/qualifier/P585> ?var25  } GROUP BY ?var21 ?var24  }
}
