
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var11  <http://www.wikidata.org/prop/P793>  [  <http://www.wikidata.org/prop/statement/P793>  <http://www.wikidata.org/entity/Q331055> ;  <http://www.wikidata.org/prop/qualifier/P585>  ?var12  ] .   ?var11  <http://www.wikidata.org/prop/direct/P4602>  ?var13 .  FILTER (  ( (  ABS (  (  ?var12 - ?var13  )  )  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var21  <http://www.wikidata.org/prop/P793>  [  <http://www.wikidata.org/prop/statement/P793>  <http://www.wikidata.org/entity/Q331055> ;  <http://www.wikidata.org/prop/qualifier/P585>  ?var22  ] .   ?var21  <http://www.wikidata.org/prop/direct/P4602>  ?var23 .  FILTER (  ( (  ABS (  (  ?var22 - ?var23  )  )  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . }  }
}
