
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 ?var14 ?var15 ?var16 ?var17 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q26529> ;      <http://www.wikidata.org/prop/direct/P619> ?var17 ;      <http://www.wikidata.org/prop/direct/P1427> ?var13 ;      <http://www.wikidata.org/prop/direct/P375> ?var18 .   ?var18 <http://www.wikidata.org/prop/direct/P516> ?var12 .   ?var12 <http://www.wikidata.org/prop/direct/P495> ?var14 .   ?var14 <http://www.wikidata.org/prop/direct/P625> ?var16  }  }
SIMILARITY JOIN ON ( ?var17 ) ( ?var27 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 ?var24 ?var25 ?var26 ?var27 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q26529> ;      <http://www.wikidata.org/prop/direct/P619> ?var27 ;      <http://www.wikidata.org/prop/direct/P1427> ?var23 ;      <http://www.wikidata.org/prop/direct/P375> ?var28 .   ?var28 <http://www.wikidata.org/prop/direct/P516> ?var22 .   ?var22 <http://www.wikidata.org/prop/direct/P495> ?var24 .   ?var24 <http://www.wikidata.org/prop/direct/P625> ?var26  }  }
}
