
SELECT * WHERE {
{ SELECT ?var11 ( COUNT (* ) AS  ?var12  ) WHERE {   <http://www.wikidata.org/entity/Q42>  ?var13  ?var14 .   ?var11  <http://wikiba.se/ontology#claim>  ?var13 . } GROUP BY  ?var11   HAVING  ( (  ?var12  = "19"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT (* ) AS  ?var22  ) WHERE {   <http://www.wikidata.org/entity/Q42>  ?var23  ?var24 .   ?var21  <http://wikiba.se/ontology#claim>  ?var23 . } GROUP BY  ?var21   HAVING  ( (  ?var22  = "19"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
