
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT (* ) AS  ?var13  ) WHERE {   VALUES (  ?var11  ) {    (  <http://www.wikidata.org/prop/direct/P2013>  )   }   ?var11  ?var14  ?var12 . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT (* ) AS  ?var23  ) WHERE {   VALUES (  ?var21  ) {    (  <http://www.wikidata.org/prop/direct/P2013>  )   }   ?var21  ?var24  ?var22 . } GROUP BY  ?var21  ?var22   }
}
