
SELECT * WHERE {
{ SELECT ?var11 (COUNT(DISTINCT ?var12) AS ?var13) WHERE  { VALUES ?var14 { <http://www.wikidata.org/entity/Q148> <http://www.wikidata.org/entity/Q29520> <http://www.wikidata.org/entity/Q865> }   ?var11 <http://www.wikidata.org/prop/direct/P27> ?var14 .   ?var15 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424> ;      <http://www.wikidata.org/prop/direct/P57> ?var11 ;      <http://www.wikidata.org/prop/direct/P2047> ?var12  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(DISTINCT ?var22) AS ?var23) WHERE  { VALUES ?var24 { <http://www.wikidata.org/entity/Q148> <http://www.wikidata.org/entity/Q29520> <http://www.wikidata.org/entity/Q865> }   ?var21 <http://www.wikidata.org/prop/direct/P27> ?var24 .   ?var25 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424> ;      <http://www.wikidata.org/prop/direct/P57> ?var21 ;      <http://www.wikidata.org/prop/direct/P2047> ?var22  } GROUP BY ?var21  }
}
