
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ?var12 ?var13 ?var14 ?var15 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q6256> ;      <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q48> ;      <http://www.wikidata.org/prop/direct/P1082> ?var12 ;      <http://www.wikidata.org/prop/direct/P2132> ?var13 ;      <http://www.wikidata.org/prop/direct/P2219> ?var14 ;      <http://www.wikidata.org/prop/direct/P1279> ?var15  }  }
SIMILARITY JOIN ON ( ?var13, ?var14, ?var15 ) ( ?var23, ?var24, ?var25 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ?var22 ?var23 ?var24 ?var25 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q6256> ;      <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/entity/Q48> ;      <http://www.wikidata.org/prop/direct/P1082> ?var22 ;      <http://www.wikidata.org/prop/direct/P2132> ?var23 ;      <http://www.wikidata.org/prop/direct/P2219> ?var24 ;      <http://www.wikidata.org/prop/direct/P1279> ?var25  }  }
}
