
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P1080>  <http://www.wikidata.org/entity/Q20203549> .   ?var11  ?var12  ?var14 . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P1080>  <http://www.wikidata.org/entity/Q20203549> .   ?var21  ?var22  ?var24 . } GROUP BY  ?var21   }
}
