
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { VALUES ?var11 { "WP550" }   ?var14 <http://www.wikidata.org/prop/direct/P2410> ?var11 ;      <http://www.wikidata.org/prop/direct/P2888> ?var15 ;      <http://www.wikidata.org/prop/direct/P527> ?var12 ;      <http://www.wikidata.org/prop/direct/P703> <http://www.wikidata.org/entity/Q15978631> .   ?var12 <http://www.wikidata.org/prop/direct/P1117> ?var13  }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { VALUES ?var21 { "WP550" }   ?var24 <http://www.wikidata.org/prop/direct/P2410> ?var21 ;      <http://www.wikidata.org/prop/direct/P2888> ?var25 ;      <http://www.wikidata.org/prop/direct/P527> ?var22 ;      <http://www.wikidata.org/prop/direct/P703> <http://www.wikidata.org/entity/Q15978631> .   ?var22 <http://www.wikidata.org/prop/direct/P1117> ?var23  }  }
}
