
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( DISTINCT  ?var12  ) AS  ?var13  ) WHERE {   BIND (  LANG (  ?var14Label  )  AS  ?var12 ).   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q34763> .   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14Label . } GROUP BY  ?var11   HAVING  ( ( COUNT ( DISTINCT  ?var12  ) >= "10"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( DISTINCT  ?var22  ) AS  ?var23  ) WHERE {   BIND (  LANG (  ?var24Label  )  AS  ?var22 ).   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q34763> .   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24Label . } GROUP BY  ?var21   HAVING  ( ( COUNT ( DISTINCT  ?var22  ) >= "10"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
