
SELECT * WHERE {
{ SELECT ?var11  ?var11Label  ?var12  ?var12Label  ?var13  WHERE {  SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  )  WHERE  {    ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .    ?var11  <http://www.wikidata.org/prop/P39>  ?var14 .    ?var14  <http://www.wikidata.org/prop/statement/P39>  <http://www.wikidata.org/entity/Q11696> .    ?var14  <http://www.wikidata.org/prop/qualifier/P580>  ?var15 .    ?var11  <http://www.wikidata.org/prop/direct/P40>  ?var12 .    ?var11  <http://www.wikidata.org/prop/direct/P40>  ?var12 .  }  GROUP BY  ?var11  }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var21Label  ?var22  ?var22Label  ?var23  WHERE {  SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  )  WHERE  {    ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .    ?var21  <http://www.wikidata.org/prop/P39>  ?var24 .    ?var24  <http://www.wikidata.org/prop/statement/P39>  <http://www.wikidata.org/entity/Q11696> .    ?var24  <http://www.wikidata.org/prop/qualifier/P580>  ?var25 .    ?var21  <http://www.wikidata.org/prop/direct/P40>  ?var22 .    ?var21  <http://www.wikidata.org/prop/direct/P40>  ?var22 .  }  GROUP BY  ?var21  }  }
}
