
SELECT * WHERE {
{ SELECT ?var11  ?var12  WHERE {   ?var12  <http://www.wikidata.org/prop/direct/P1114>  ?var11 . }  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  WHERE {   ?var22  <http://www.wikidata.org/prop/direct/P1114>  ?var21 . }  }
}
