
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P2021> ?var12   MINUS    { ?var13 <http://www.wikidata.org/prop/direct/P50> ?var11 }  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P2021> ?var22   MINUS    { ?var23 <http://www.wikidata.org/prop/direct/P50> ?var21 }  }  }
}
