
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 ?var14 WHERE  { ?var11 <http://www.wikidata.org/entity/Q5> ?var15 ;      <http://www.wikidata.org/prop/direct/P1448> ?var12 ;      <http://www.wikidata.org/prop/direct/P1329> ?var13 ;      <http://www.wikidata.org/prop/direct/P3629> ?var14  }  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 ?var24 WHERE  { ?var21 <http://www.wikidata.org/entity/Q5> ?var25 ;      <http://www.wikidata.org/prop/direct/P1448> ?var22 ;      <http://www.wikidata.org/prop/direct/P1329> ?var23 ;      <http://www.wikidata.org/prop/direct/P3629> ?var24  }  }
}
