
SELECT * WHERE {
{ SELECT (COUNT(?var11) AS ?var12) ?var11 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q79007> ;      <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q213>  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT (COUNT(?var21) AS ?var22) ?var21 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q79007> ;      <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q213>  } GROUP BY ?var21  }
}
