
SELECT * WHERE {
{ SELECT ?var11Label ( COUNT ( ?var11  ) AS  ?var12  ) WHERE {   BIND (  YEAR (  ?var13  )  AS  ?var14 ).   ?var15  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q215380> .   ?var15  <http://www.wikidata.org/prop/direct/P571>  ?var13 .   ?var15  <http://www.wikidata.org/prop/direct/P136>  ?var11 .   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11Label .  FILTER (  ( (  LANG (  ?var11Label  )  =  "en" ) )  ) .  FILTER (  ( (  ?var14  > "1900"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11Label   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21Label ( COUNT ( ?var21  ) AS  ?var22  ) WHERE {   BIND (  YEAR (  ?var23  )  AS  ?var24 ).   ?var25  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q215380> .   ?var25  <http://www.wikidata.org/prop/direct/P571>  ?var23 .   ?var25  <http://www.wikidata.org/prop/direct/P136>  ?var21 .   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21Label .  FILTER (  ( (  LANG (  ?var21Label  )  =  "en" ) )  ) .  FILTER (  ( (  ?var24  > "1900"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21Label   }
}
