
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { { BIND(str(year(?var14)) AS ?var11)    ?var12 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q7889> ;       <http://www.wikidata.org/prop/direct/P400> <http://www.wikidata.org/entity/Q23882> ;       <http://www.wikidata.org/prop/direct/P577> ?var14 ;       <http://www.wikidata.org/prop/direct/P136> ?var15   }   FILTER ( ?var14 >= "2000-00-00T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { { BIND(str(year(?var24)) AS ?var21)    ?var22 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q7889> ;       <http://www.wikidata.org/prop/direct/P400> <http://www.wikidata.org/entity/Q23882> ;       <http://www.wikidata.org/prop/direct/P577> ?var24 ;       <http://www.wikidata.org/prop/direct/P136> ?var25   }   FILTER ( ?var24 >= "2000-00-00T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var21  }
}
