
SELECT * WHERE {
{ SELECT ?var11 ?var12Label (COUNT(?var13) AS ?var14) WHERE  { { { SELECT ?var13 ?var11     WHERE      { ?var13 <http://www.wikidata.org/prop/direct/P106> ?var11 .       ?var11 (<http://www.wikidata.org/prop/direct/P279>)+ <http://www.wikidata.org/entity/Q33999> .       ?var13 <http://www.wikidata.org/prop/direct/P569> ?var15       FILTER ( year(?var15) > 1930 )      }     LIMIT  3000    }    ?var13 <http://www.wikidata.org/prop/direct/P106> ?var16 .    ?var16 (<http://www.wikidata.org/prop/direct/P279>)+ <http://www.wikidata.org/entity/Q33999> .    ?var16 <http://www.w3.org/2000/01/rdf-schema#label> ?var12Label   }   FILTER ( ?var16 != <http://www.wikidata.org/entity/Q33999> )   FILTER ( lang(?var12Label) = "fr" )  } GROUP BY ?var11 ?var16 ?var12Label  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22Label (COUNT(?var23) AS ?var24) WHERE  { { { SELECT ?var23 ?var21     WHERE      { ?var23 <http://www.wikidata.org/prop/direct/P106> ?var21 .       ?var21 (<http://www.wikidata.org/prop/direct/P279>)+ <http://www.wikidata.org/entity/Q33999> .       ?var23 <http://www.wikidata.org/prop/direct/P569> ?var25       FILTER ( year(?var25) > 1930 )      }     LIMIT  3000    }    ?var23 <http://www.wikidata.org/prop/direct/P106> ?var26 .    ?var26 (<http://www.wikidata.org/prop/direct/P279>)+ <http://www.wikidata.org/entity/Q33999> .    ?var26 <http://www.w3.org/2000/01/rdf-schema#label> ?var22Label   }   FILTER ( ?var26 != <http://www.wikidata.org/entity/Q33999> )   FILTER ( lang(?var22Label) = "fr" )  } GROUP BY ?var21 ?var26 ?var22Label  }
}
