
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var12 ?var14         ?var15 .   ?var15 <http://www.wikidata.org/prop/P1534> ?var16 ;      <http://www.wikidata.org/prop/statement/P1534> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var22 ?var24         ?var25 .   ?var25 <http://www.wikidata.org/prop/P1534> ?var26 ;      <http://www.wikidata.org/prop/statement/P1534> ?var21  } GROUP BY ?var21  }
}
