
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   BIND (  LANG (  ?var14  )  AS  ?var11 ).   ?var12  <http://www.wikidata.org/prop/direct/P179>  <http://www.wikidata.org/entity/Q18516851> .   ?var12  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14 . } GROUP BY  ?var11   HAVING  ( (  ?var13  > "23"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   BIND (  LANG (  ?var24  )  AS  ?var21 ).   ?var22  <http://www.wikidata.org/prop/direct/P179>  <http://www.wikidata.org/entity/Q18516851> .   ?var22  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24 . } GROUP BY  ?var21   HAVING  ( (  ?var23  > "23"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
