
SELECT * WHERE {
{ SELECT DISTINCT ?var11  ?var11Label  ?var12  WHERE {  {   SELECT ?var11 ( COUNT ( DISTINCT  ?var13  ) AS  ?var12  )   WHERE   {     ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .     ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q134556> .     ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7366> .     ?var13  <http://www.wikidata.org/prop/direct/P162>  ?var11 .     ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var13Label .   }   GROUP BY  ?var11   }   ?var11  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q183945> .   ?var11  <http://www.wikidata.org/prop/direct/P166>  ?var14 .   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11Label .  FILTER (  ( (  LANG (  ?var11Label  )  =  "en" ) )  ) . }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21  ?var21Label  ?var22  WHERE {  {   SELECT ?var21 ( COUNT ( DISTINCT  ?var23  ) AS  ?var22  )   WHERE   {     ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .     ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q134556> .     ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7366> .     ?var23  <http://www.wikidata.org/prop/direct/P162>  ?var21 .     ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var23Label .   }   GROUP BY  ?var21   }   ?var21  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q183945> .   ?var21  <http://www.wikidata.org/prop/direct/P166>  ?var24 .   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21Label .  FILTER (  ( (  LANG (  ?var21Label  )  =  "en" ) )  ) . }  }
}
