
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13 ( COUNT ( ?var12  ) AS  ?var14  ) WHERE {   BIND (  (  NOW (  ) - ?var13  )  AS  ?var15 ).   ?var11  <http://www.wikidata.org/prop/direct/P2924>  ?var12 ;  <http://schema.org/dateModified>  ?var13 .  FILTER (  ( (  ?var15  < "8"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11  ?var12  ?var13   HAVING  ( (  ?var14  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23 ( COUNT ( ?var22  ) AS  ?var24  ) WHERE {   BIND (  (  NOW (  ) - ?var23  )  AS  ?var25 ).   ?var21  <http://www.wikidata.org/prop/direct/P2924>  ?var22 ;  <http://schema.org/dateModified>  ?var23 .  FILTER (  ( (  ?var25  < "8"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21  ?var22  ?var23   HAVING  ( (  ?var24  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
