
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) WHERE  { { { BIND(year(?var13) AS ?var11)     BIND(?var15Label AS ?var12)    }    ?var16 <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183> ;       <http://www.wikidata.org/prop/direct/P569> ?var13 ;       <http://www.wikidata.org/prop/direct/P21> ?var15   }   FILTER ( ?var11 >= 1700 )  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) WHERE  { { { BIND(year(?var23) AS ?var21)     BIND(?var25Label AS ?var22)    }    ?var26 <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q183> ;       <http://www.wikidata.org/prop/direct/P569> ?var23 ;       <http://www.wikidata.org/prop/direct/P21> ?var25   }   FILTER ( ?var21 >= 1700 )  } GROUP BY ?var21 ?var22  }
}
