
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { VALUES ?var11 { <http://www.wikidata.org/entity/Q24056317> <http://www.wikidata.org/entity/Q766782> }   ?var11 <http://www.wikidata.org/prop/direct/P170> ?var12 ;      <http://www.wikidata.org/prop/direct/P256> ?var14  } GROUP BY ?var11 LIMIT  100  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { VALUES ?var21 { <http://www.wikidata.org/entity/Q24056317> <http://www.wikidata.org/entity/Q766782> }   ?var21 <http://www.wikidata.org/prop/direct/P170> ?var22 ;      <http://www.wikidata.org/prop/direct/P256> ?var24  } GROUP BY ?var21 LIMIT  100  }
}
