
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { VALUES ?var12 { <http://www.wikidata.org/entity/Q1782926> <http://www.wikidata.org/entity/Q167920> }   ?var11 <http://www.wikidata.org/prop/direct/P69> ?var12 ;      <http://www.wikidata.org/prop/direct/P569> ?var14 ;      <http://www.wikidata.org/prop/direct/P570> ?var15  } GROUP BY ?var11 HAVING ( ?var13 > 1 )  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { VALUES ?var22 { <http://www.wikidata.org/entity/Q1782926> <http://www.wikidata.org/entity/Q167920> }   ?var21 <http://www.wikidata.org/prop/direct/P69> ?var22 ;      <http://www.wikidata.org/prop/direct/P569> ?var24 ;      <http://www.wikidata.org/prop/direct/P570> ?var25  } GROUP BY ?var21 HAVING ( ?var23 > 1 )  }
}
