
SELECT * WHERE {
{ SELECT ?var11 (count(*) AS ?var12) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P1937> ?var13 ;      <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/P238>  } GROUP BY ?var11 HAVING ( ?var12 > 1 )  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (count(*) AS ?var22) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P1937> ?var23 ;      <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/P238>  } GROUP BY ?var21 HAVING ( ?var22 > 1 )  }
}
