
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P4009>  ?var12 .  FILTER (  ( (  ?var14  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P4009>  ?var22 .  FILTER (  ( (  ?var24  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21  ?var22   }
}
