
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var11  ) AS  ?var13  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P4009>  ?var12 .  FILTER (  ( (  ?var13  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var21  ) AS  ?var23  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P4009>  ?var22 .  FILTER (  ( (  ?var23  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21  ?var22   }
}
