
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P2293> <http://www.wikidata.org/entity/Q188874> ;      <http://www.wikidata.org/prop/direct/P1057> <http://www.wikidata.org/entity/Q780468> ;      <http://www.wikidata.org/prop/direct/P644> ?var12   FILTER ( str(?var12) = "48919853" )  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P2293> <http://www.wikidata.org/entity/Q188874> ;      <http://www.wikidata.org/prop/direct/P1057> <http://www.wikidata.org/entity/Q780468> ;      <http://www.wikidata.org/prop/direct/P644> ?var22   FILTER ( str(?var22) = "48919853" )  }  }
}
