
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ?var12 ?var13 WHERE  { <http://www.wikidata.org/entity/Q11344>        <http://www.wikidata.org/prop/direct/P246> ?var11 ;        <http://www.wikidata.org/prop/direct/P1086> ?var11  }  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ?var22 ?var23 WHERE  { <http://www.wikidata.org/entity/Q11344>        <http://www.wikidata.org/prop/direct/P246> ?var21 ;        <http://www.wikidata.org/prop/direct/P1086> ?var21  }  }
}
