
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ?var12 (COUNT(?var13) AS ?var14) WHERE  { { ?var11 ?var15         ?var12 .    ?var12 <http://www.wikidata.org/prop/qualifier/P1013> ?var13    VALUES ?var16 { <http://www.wikidata.org/entity/Q4167836> <http://www.wikidata.org/entity/Q5> }   }   ?var13 <http://www.wikidata.org/prop/direct/P31> ?var16  } GROUP BY ?var11 ?var12 HAVING ( ?var14 > 2 ) LIMIT  400  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ?var22 (COUNT(?var23) AS ?var24) WHERE  { { ?var21 ?var25         ?var22 .    ?var22 <http://www.wikidata.org/prop/qualifier/P1013> ?var23    VALUES ?var26 { <http://www.wikidata.org/entity/Q4167836> <http://www.wikidata.org/entity/Q5> }   }   ?var23 <http://www.wikidata.org/prop/direct/P31> ?var26  } GROUP BY ?var21 ?var22 HAVING ( ?var24 > 2 ) LIMIT  400  }
}
