
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { { { BIND(( ( ?var14 - ?var15 ) / 2 ) AS ?var16)     BIND(if(( ?var16 = 0 ), ?var17, concat(str(?var17), "±", str(?var16))) AS ?var18)    }    BIND(( ?var17 * ?var19 ) AS ?var13)   }   ?var11  <http://www.wikidata.org/prop/direct/P2101> ?var12 .   ?var12  <http://www.wikidata.org/prop/statement/value/P2101> ?var110 .   ?var110 <http://wikiba.se/ontology#quantityAmount> ?var17 ;       <http://wikiba.se/ontology#quantityUnit> ?var111 ;       <http://wikiba.se/ontology#quantityLowerBound> ?var15 ;       <http://wikiba.se/ontology#quantityUpperBound> ?var14 .   ?var111 <http://www.wikidata.org/prop/P2370> ?var112 .   ?var112 <http://www.wikidata.org/prop/statement/value/P2370> ?var113 .   ?var113 <http://wikiba.se/ontology#quantityAmount> ?var19 ;       <http://wikiba.se/ontology#quantityUnit> <http://www.wikidata.org/entity/Q11579>  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { { { BIND(( ( ?var24 - ?var25 ) / 2 ) AS ?var26)     BIND(if(( ?var26 = 0 ), ?var27, concat(str(?var27), "±", str(?var26))) AS ?var28)    }    BIND(( ?var27 * ?var29 ) AS ?var23)   }   ?var21  <http://www.wikidata.org/prop/direct/P2101> ?var22 .   ?var22  <http://www.wikidata.org/prop/statement/value/P2101> ?var210 .   ?var210 <http://wikiba.se/ontology#quantityAmount> ?var27 ;       <http://wikiba.se/ontology#quantityUnit> ?var211 ;       <http://wikiba.se/ontology#quantityLowerBound> ?var25 ;       <http://wikiba.se/ontology#quantityUpperBound> ?var24 .   ?var211 <http://www.wikidata.org/prop/P2370> ?var212 .   ?var212 <http://www.wikidata.org/prop/statement/value/P2370> ?var213 .   ?var213 <http://wikiba.se/ontology#quantityAmount> ?var29 ;       <http://wikiba.se/ontology#quantityUnit> <http://www.wikidata.org/entity/Q11579>  }  }
}
