
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( DISTINCT  ?var12  ) AS  ?var13  ) WHERE {   ?var14  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  ?var11 .   ?var14  <http://www.w3.org/2000/01/rdf-schema#sameAs>  ?var12 .  FILTER (  (  REGEX (  STR (  ?var12  ) , "string1" )  )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( DISTINCT  ?var22  ) AS  ?var23  ) WHERE {   ?var24  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  ?var21 .   ?var24  <http://www.w3.org/2000/01/rdf-schema#sameAs>  ?var22 .  FILTER (  (  REGEX (  STR (  ?var22  ) , "string1" )  )  ) . } GROUP BY  ?var21   }
}
