
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   BIND (  YEAR (  ?var14  )  AS  ?var11 ).   ?var12  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3331189> ;  <http://www.wikidata.org/prop/direct/P577>  ?var14 .   ?var15  <http://schema.org/about>  ?var12 .   ?var15  <http://schema.org/isPartOf>  <https://fr.wikisource.org/> .  FILTER (  ( (  ?var11  > "1000"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   BIND (  YEAR (  ?var24  )  AS  ?var21 ).   ?var22  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3331189> ;  <http://www.wikidata.org/prop/direct/P577>  ?var24 .   ?var25  <http://schema.org/about>  ?var22 .   ?var25  <http://schema.org/isPartOf>  <https://fr.wikisource.org/> .  FILTER (  ( (  ?var21  > "1000"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21   }
}
