
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q1048390> .   ?var14  <http://www.wikidata.org/prop/direct/P2067>  ?var11 .   ?var14  <http://www.wikidata.org/prop/direct/P2386>  ?var12 . } LIMIT 10  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q1048390> .   ?var24  <http://www.wikidata.org/prop/direct/P2067>  ?var21 .   ?var24  <http://www.wikidata.org/prop/direct/P2386>  ?var22 . } LIMIT 10  }
}
