
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;      <http://www.wikidata.org/prop/direct/P20> ?var14 ;      <http://www.wikidata.org/prop/direct/P2873> ?var12 .   ?var14 <http://www.wikidata.org/prop/direct/P625> ?var13   FILTER ( ?var12 > 0 )  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q5> ;      <http://www.wikidata.org/prop/direct/P20> ?var24 ;      <http://www.wikidata.org/prop/direct/P2873> ?var22 .   ?var24 <http://www.wikidata.org/prop/direct/P625> ?var23   FILTER ( ?var22 > 0 )  }  }
}
