
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) ?var15 WHERE  { { BIND(concat(?var16, " eyes") AS ?var11)    ?var13 <http://www.wikidata.org/prop/direct/P1340> ?var15 ;       <http://www.wikidata.org/prop/direct/P1884> ?var12 ;       <http://www.wikidata.org/prop/direct/P2048> ?var17 .    ?var15 <http://www.w3.org/2000/01/rdf-schema#label> ?var16   }   FILTER ( lang(?var16) = "en" )  } GROUP BY ?var11 ?var12 ?var15  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) ?var25 WHERE  { { BIND(concat(?var26, " eyes") AS ?var21)    ?var23 <http://www.wikidata.org/prop/direct/P1340> ?var25 ;       <http://www.wikidata.org/prop/direct/P1884> ?var22 ;       <http://www.wikidata.org/prop/direct/P2048> ?var27 .    ?var25 <http://www.w3.org/2000/01/rdf-schema#label> ?var26   }   FILTER ( lang(?var26) = "en" )  } GROUP BY ?var21 ?var22 ?var25  }
}
