
SELECT * WHERE {
{ SELECT( COUNT ( ?var11  ) AS  ?var12  ) ?var11  ?var13  ?var14  ?var15  ?var16  WHERE {   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  "string1";  <http://www.wikidata.org/prop/direct/P19>  ?var13 ;  <http://www.wikidata.org/prop/direct/P20>  ?var14 .   ?var13  <http://www.wikidata.org/prop/direct/P625>  ?var16 .   ?var14  <http://www.wikidata.org/prop/direct/P625>  ?var15 . } GROUP BY  ?var11  ?var13  ?var14  ?var15  ?var16   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT( COUNT ( ?var21  ) AS  ?var22  ) ?var21  ?var23  ?var24  ?var25  ?var26  WHERE {   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  "string1";  <http://www.wikidata.org/prop/direct/P19>  ?var23 ;  <http://www.wikidata.org/prop/direct/P20>  ?var24 .   ?var23  <http://www.wikidata.org/prop/direct/P625>  ?var26 .   ?var24  <http://www.wikidata.org/prop/direct/P625>  ?var25 . } GROUP BY  ?var21  ?var23  ?var24  ?var25  ?var26   }
}
