
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q4830453> ;      <http://www.wikidata.org/prop/direct/P2139> ?var12   FILTER regex(?var11, "bosch", "i")  } LIMIT  10  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q4830453> ;      <http://www.wikidata.org/prop/direct/P2139> ?var22   FILTER regex(?var21, "bosch", "i")  } LIMIT  10  }
}
