
SELECT * WHERE {
{ SELECT ?var11 ?var12Label ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q4830453> ;      <http://www.wikidata.org/prop/direct/P2139> ?var13 ;      <http://www.w3.org/2000/01/rdf-schema#label> ?var12Label   FILTER regex(?var12Label, "bosch", "i")  } LIMIT  100  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22Label ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q4830453> ;      <http://www.wikidata.org/prop/direct/P2139> ?var23 ;      <http://www.w3.org/2000/01/rdf-schema#label> ?var22Label   FILTER regex(?var22Label, "bosch", "i")  } LIMIT  100  }
}
