
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { <http://www.wikidata.org/entity/Q42267>        <http://www.wikidata.org/prop/direct/P1352> ?var11 .   <http://www.wikidata.org/prop/P1352>        ?var12         ?var13  } LIMIT  1  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { <http://www.wikidata.org/entity/Q42267>        <http://www.wikidata.org/prop/direct/P1352> ?var21 .   <http://www.wikidata.org/prop/P1352>        ?var22         ?var23  } LIMIT  1  }
}
