
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { <http://www.wikidata.org/entity/Q42267>        <http://www.wikidata.org/prop/direct/P1352> ?var11 .   <http://www.wikidata.org/prop/direct/P1352>        ?var13         ?var12  } LIMIT  1  }
SIMILARITY JOIN ON ( ?var11 ) ( ?var21 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { <http://www.wikidata.org/entity/Q42267>        <http://www.wikidata.org/prop/direct/P1352> ?var21 .   <http://www.wikidata.org/prop/direct/P1352>        ?var23         ?var22  } LIMIT  1  }
}
