
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P17> ?var12 ;      <http://www.wikidata.org/prop/direct/P2132> ?var13  } LIMIT  100  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P17> ?var22 ;      <http://www.wikidata.org/prop/direct/P2132> ?var23  } LIMIT  100  }
}
