
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 ?var14 ?var15 (COUNT(DISTINCT ?var16) AS ?var17) ?var18 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P1216> ?var12 ;      <http://www.wikidata.org/prop/direct/P18> ?var13 ;      <http://www.wikidata.org/prop/direct/P625> ?var14 ;      <http://www.wikidata.org/prop/direct/P1435> ?var15 ;      <http://www.wikidata.org/prop/direct/P31> ?var16 ;      <http://www.wikidata.org/prop/direct/P131> ?var18   FILTER regex(?var12, "^(1000)")  } GROUP BY ?var11 ?var12 ?var13 ?var14 ?var15 ?var18  }
SIMILARITY JOIN ON ( ?var17 ) ( ?var27 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 ?var24 ?var25 (COUNT(DISTINCT ?var26) AS ?var27) ?var28 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P1216> ?var22 ;      <http://www.wikidata.org/prop/direct/P18> ?var23 ;      <http://www.wikidata.org/prop/direct/P625> ?var24 ;      <http://www.wikidata.org/prop/direct/P1435> ?var25 ;      <http://www.wikidata.org/prop/direct/P31> ?var26 ;      <http://www.wikidata.org/prop/direct/P131> ?var28   FILTER regex(?var22, "^(1000)")  } GROUP BY ?var21 ?var22 ?var23 ?var24 ?var25 ?var28  }
}
