
SELECT * WHERE {
{ SELECT ?var11  ?var11Label ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var12  <http://www.wikidata.org/prop/direct/P19>  ?var14 ;  <http://www.wikidata.org/prop/direct/P106>  ?var15 .   ?var14  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .   ?var15  <http://www.wikidata.org/prop/direct/P279>  <http://www.wikidata.org/entity/Q82955> . } GROUP BY  ?var11  ?var11Label   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var21Label ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var22  <http://www.wikidata.org/prop/direct/P19>  ?var24 ;  <http://www.wikidata.org/prop/direct/P106>  ?var25 .   ?var24  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q36> .   ?var25  <http://www.wikidata.org/prop/direct/P279>  <http://www.wikidata.org/entity/Q82955> . } GROUP BY  ?var21  ?var21Label   }
}
