
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   VALUES (  ?var11  ) {    (  <http://www.wikidata.org/entity/Q41427943>  )    (  <http://www.wikidata.org/entity/Q41411330>  )   }   ?var11  <http://www.wikidata.org/prop/P625>  ?var14 .   ?var14  <http://www.wikidata.org/prop/statement/value/P625>  ?var15 .   ?var15  <http://wikiba.se/ontology#geoPrecision>  ?var12 . } GROUP BY  ?var11   HAVING  ( (  ?var13  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   VALUES (  ?var21  ) {    (  <http://www.wikidata.org/entity/Q41427943>  )    (  <http://www.wikidata.org/entity/Q41411330>  )   }   ?var21  <http://www.wikidata.org/prop/P625>  ?var24 .   ?var24  <http://www.wikidata.org/prop/statement/value/P625>  ?var25 .   ?var25  <http://wikiba.se/ontology#geoPrecision>  ?var22 . } GROUP BY  ?var21   HAVING  ( (  ?var23  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
