
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) ?var12 WHERE  { { BIND(str(year(?var14)) AS ?var11)    ?var15 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q571> ;       <http://www.wikidata.org/prop/direct/P577> ?var14 ;       <http://www.wikidata.org/prop/direct/P136> ?var12   }   FILTER ( ?var14 >= "2000-00-00T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var12 ?var11 HAVING ( ?var13 > 10 )  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) ?var22 WHERE  { { BIND(str(year(?var24)) AS ?var21)    ?var25 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q571> ;       <http://www.wikidata.org/prop/direct/P577> ?var24 ;       <http://www.wikidata.org/prop/direct/P136> ?var22   }   FILTER ( ?var24 >= "2000-00-00T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> )  } GROUP BY ?var22 ?var21 HAVING ( ?var23 > 10 )  }
}
