
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P40>  ?var12 .   ?var12  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12Label . } GROUP BY  ?var11  LIMIT 1  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P40>  ?var22 .   ?var22  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22Label . } GROUP BY  ?var21  LIMIT 1  }
}
