
SELECT * WHERE {
{ SELECT DISTINCT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P40>  ?var13 .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var13Label . } GROUP BY  ?var11  ?var12  LIMIT 1  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P40>  ?var23 .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var23Label . } GROUP BY  ?var21  ?var22  LIMIT 1  }
}
