
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var14 <http://www.wikidata.org/prop/direct/P4389> ?var15 ;      <http://www.wikidata.org/prop/direct/P106> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var24 <http://www.wikidata.org/prop/direct/P4389> ?var25 ;      <http://www.wikidata.org/prop/direct/P106> ?var21  } GROUP BY ?var21  }
}
