
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) WHERE  { VALUES ?var11 { <http://www.wikidata.org/prop/direct/P580> <http://www.wikidata.org/prop/direct/P582> <http://www.wikidata.org/prop/direct/P155> <http://www.wikidata.org/prop/direct/P156> <http://www.wikidata.org/prop/direct/P571> <http://www.wikidata.org/prop/direct/P576> <http://www.wikidata.org/prop/direct/P1365> <http://www.wikidata.org/prop/direct/P1366> <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/prop/direct/P1269> }   ?var13 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q6428674> ;      ?var11         _:b0 .   ?var12 ?var15         ?var11 ;      a           <http://wikiba.se/ontology#Property>  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) WHERE  { VALUES ?var21 { <http://www.wikidata.org/prop/direct/P580> <http://www.wikidata.org/prop/direct/P582> <http://www.wikidata.org/prop/direct/P155> <http://www.wikidata.org/prop/direct/P156> <http://www.wikidata.org/prop/direct/P571> <http://www.wikidata.org/prop/direct/P576> <http://www.wikidata.org/prop/direct/P1365> <http://www.wikidata.org/prop/direct/P1366> <http://www.wikidata.org/prop/direct/P361> <http://www.wikidata.org/prop/direct/P1269> }   ?var23 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q6428674> ;      ?var21         _:b0 .   ?var22 ?var25         ?var21 ;      a           <http://wikiba.se/ontology#Property>  } GROUP BY ?var21 ?var22  }
}
