
SELECT * WHERE {
{ SELECT ?var11Label ( COUNT ( ?var11  ) AS  ?var12  ) WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P106>  ?var11 .   ?var14  <http://schema.org/about>  ?var13 .   ?var14  <http://schema.org/isPartOf>  <https://fr.wikisource.org/> .  FILTER (  ( (  ?var12  > "100"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11Label   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21Label ( COUNT ( ?var21  ) AS  ?var22  ) WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P106>  ?var21 .   ?var24  <http://schema.org/about>  ?var23 .   ?var24  <http://schema.org/isPartOf>  <https://fr.wikisource.org/> .  FILTER (  ( (  ?var22  > "100"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21Label   }
}
