
SELECT * WHERE {
{ SELECT ?var11 ( COUNT (* ) AS  ?var12  ) WHERE {   BIND (  CEIL (  (  <http://www.w3.org/2001/XMLSchema#integer>  ( SUBSTR (  STR (  ?var13  ) ,"33"^^<http://www.w3.org/2001/XMLSchema#integer>  ) ) /"100000"^^<http://www.w3.org/2001/XMLSchema#integer>  )  )  AS  ?var11 ).   ?var13  <http://www.w3.org/2002/07/owl#sameAs>  [] . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT (* ) AS  ?var22  ) WHERE {   BIND (  CEIL (  (  <http://www.w3.org/2001/XMLSchema#integer>  ( SUBSTR (  STR (  ?var23  ) ,"33"^^<http://www.w3.org/2001/XMLSchema#integer>  ) ) /"100000"^^<http://www.w3.org/2001/XMLSchema#integer>  )  )  AS  ?var21 ).   ?var23  <http://www.w3.org/2002/07/owl#sameAs>  [] . } GROUP BY  ?var21   }
}
