
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   BIND (  YEAR (  ?var11  )  AS  ?var11 ).   BIND (  (  ?var11 - YEAR (  ?var14  )  )  AS  ?var15 ).   ?var12  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> ;  <http://www.wikidata.org/prop/direct/P569>  ?var14 ;  <http://www.wikidata.org/prop/direct/P570>  ?var11 .   ?var16  <http://schema.org/about>  ?var12 .   ?var16  <http://schema.org/isPartOf>  <https://fr.wikisource.org/> .  FILTER (  ( (  YEAR (  ?var11  )  > "1800"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   BIND (  YEAR (  ?var21  )  AS  ?var21 ).   BIND (  (  ?var21 - YEAR (  ?var24  )  )  AS  ?var25 ).   ?var22  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> ;  <http://www.wikidata.org/prop/direct/P569>  ?var24 ;  <http://www.wikidata.org/prop/direct/P570>  ?var21 .   ?var26  <http://schema.org/about>  ?var22 .   ?var26  <http://schema.org/isPartOf>  <https://fr.wikisource.org/> .  FILTER (  ( (  YEAR (  ?var21  )  > "1800"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21   }
}
