
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var12  <http://www.wikidata.org/prop/direct/P971>  [] ;  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q4167836> .   MINUS   {     ?var12  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14 .  FILTER (    ( (  LANG (  ?var14  )  =  "fr" ) )  ) .   }   BIND (  STRAFTER (  ?var15 , "in" )  AS  ?var11 ).   ?var12  <http://www.w3.org/2000/01/rdf-schema#label>  ?var15 .  FILTER (  ( (  LANG (  ?var15  )  =  "en" ) )  ) .  FILTER (  ( (  LANG (  ?var15  )  =  "en" ) )  ) .  FILTER (  (  REGEX (  ?var15 , "string1" )  )  ) . } GROUP BY  ?var11  LIMIT 5  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var22  <http://www.wikidata.org/prop/direct/P971>  [] ;  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q4167836> .   MINUS   {     ?var22  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24 .  FILTER (    ( (  LANG (  ?var24  )  =  "fr" ) )  ) .   }   BIND (  STRAFTER (  ?var25 , "in" )  AS  ?var21 ).   ?var22  <http://www.w3.org/2000/01/rdf-schema#label>  ?var25 .  FILTER (  ( (  LANG (  ?var25  )  =  "en" ) )  ) .  FILTER (  ( (  LANG (  ?var25  )  =  "en" ) )  ) .  FILTER (  (  REGEX (  ?var25 , "string1" )  )  ) . } GROUP BY  ?var21  LIMIT 5  }
}
