
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { SELECT DISTINCT ?var11 (COUNT(?var11) AS ?var12)   WHERE    { ?var13 <http://www.wikidata.org/prop/direct/P279> ?var11 ;        <http://www.wikidata.org/prop/direct/P351> ?var14    }   GROUP BY ?var11  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { SELECT DISTINCT ?var21 (COUNT(?var21) AS ?var22)   WHERE    { ?var23 <http://www.wikidata.org/prop/direct/P279> ?var21 ;        <http://www.wikidata.org/prop/direct/P351> ?var24    }   GROUP BY ?var21  }  }
}
