
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT (* ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q46190676> ;  <http://www.wikidata.org/prop/direct/P361>  ?var11 .   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q47345468> .   ?var14  <http://www.wikidata.org/prop/direct/P2094>  ?var12 .   ?var12  <http://www.wikidata.org/prop/P2094>  [  <http://www.wikidata.org/prop/statement/P2094>  <http://www.wikidata.org/entity/Q2735683> ;  <http://www.wikidata.org/prop/qualifier/P1013>  <http://www.wikidata.org/entity/Q185836>  ] . } GROUP BY  ?var11  ?var12   HAVING  ( (  ?var13  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT (* ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q46190676> ;  <http://www.wikidata.org/prop/direct/P361>  ?var21 .   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q47345468> .   ?var24  <http://www.wikidata.org/prop/direct/P2094>  ?var22 .   ?var22  <http://www.wikidata.org/prop/P2094>  [  <http://www.wikidata.org/prop/statement/P2094>  <http://www.wikidata.org/entity/Q2735683> ;  <http://www.wikidata.org/prop/qualifier/P1013>  <http://www.wikidata.org/entity/Q185836>  ] . } GROUP BY  ?var21  ?var22   HAVING  ( (  ?var23  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
