
SELECT * WHERE {
{ SELECT ?var11 ( COUNT (* ) AS  ?var12  ) WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q46190676> ;  <http://www.wikidata.org/prop/direct/P361>  ?var11 ;  <http://www.wikidata.org/prop/direct/P2094>  ?var14 .   ?var14  <http://www.wikidata.org/prop/P2094>  [  <http://www.wikidata.org/prop/statement/P2094>  <http://www.wikidata.org/entity/Q2735683> ;  <http://www.wikidata.org/prop/qualifier/P1013>  <http://www.wikidata.org/entity/Q185836>  ] ;  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14Label .  FILTER (  ( (  LANG (  ?var14Label  )  =  "en" ) )  ) .   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q47345468> . } GROUP BY  ?var11   HAVING  ( (  ?var12  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT (* ) AS  ?var22  ) WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q46190676> ;  <http://www.wikidata.org/prop/direct/P361>  ?var21 ;  <http://www.wikidata.org/prop/direct/P2094>  ?var24 .   ?var24  <http://www.wikidata.org/prop/P2094>  [  <http://www.wikidata.org/prop/statement/P2094>  <http://www.wikidata.org/entity/Q2735683> ;  <http://www.wikidata.org/prop/qualifier/P1013>  <http://www.wikidata.org/entity/Q185836>  ] ;  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24Label .  FILTER (  ( (  LANG (  ?var24Label  )  =  "en" ) )  ) .   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q47345468> . } GROUP BY  ?var21   HAVING  ( (  ?var22  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
