
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P2410>  ?var15 ;  <http://www.wikidata.org/prop/direct/P527>  ?var13 .   ?var12  <http://www.wikidata.org/prop/direct/P3937>  ?var16 ;  <http://www.wikidata.org/prop/direct/P527>  ?var13 . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P2410>  ?var25 ;  <http://www.wikidata.org/prop/direct/P527>  ?var23 .   ?var22  <http://www.wikidata.org/prop/direct/P3937>  ?var26 ;  <http://www.wikidata.org/prop/direct/P527>  ?var23 . } GROUP BY  ?var21  ?var22   }
}
