
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( DISTINCT  ?var13  ) AS  ?var14  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P921>  <http://www.wikidata.org/entity/Q205764> .   ?var12  <http://wikiba.se/ontology#claim>  ?var15 .   ?var12  <http://wikiba.se/ontology#statementProperty>  ?var16 .   ?var11  ?var15  ?var13 .   ?var13  ?var16  ?var17 . } GROUP BY  ?var11  ?var12  ?var17   HAVING  ( (  ?var14  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( DISTINCT  ?var23  ) AS  ?var24  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P921>  <http://www.wikidata.org/entity/Q205764> .   ?var22  <http://wikiba.se/ontology#claim>  ?var25 .   ?var22  <http://wikiba.se/ontology#statementProperty>  ?var26 .   ?var21  ?var25  ?var23 .   ?var23  ?var26  ?var27 . } GROUP BY  ?var21  ?var22  ?var27   HAVING  ( (  ?var24  > "1"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
