
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var11  ) AS  ?var12  ) WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P21>  ?var14 .   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var15  <http://schema.org/about>  ?var13 ;  <http://schema.org/isPartOf>  <https://el.wikipedia.org/> .   ?var14  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var11  )  =  "el" ) )  ) .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var16Label .  FILTER (  ( (  LANG (  ?var16Label  )  =  "el" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var21  ) AS  ?var22  ) WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P21>  ?var24 .   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var25  <http://schema.org/about>  ?var23 ;  <http://schema.org/isPartOf>  <https://el.wikipedia.org/> .   ?var24  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var21  )  =  "el" ) )  ) .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var26Label .  FILTER (  ( (  LANG (  ?var26Label  )  =  "el" ) )  ) . } GROUP BY  ?var21   }
}
