
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/P569>  ?var15 .   ?var15  <http://www.wikidata.org/prop/statement/value/p569>  ?var16 .   ?var16  <http://wikiba.se/ontology#timeValue>  ?var11 .   ?var16  <http://wikiba.se/ontology#timePrecision>  ?var17 .  FILTER (  ( (  ?var17  =  "6" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/P569>  ?var25 .   ?var25  <http://www.wikidata.org/prop/statement/value/p569>  ?var26 .   ?var26  <http://wikiba.se/ontology#timeValue>  ?var21 .   ?var26  <http://wikiba.se/ontology#timePrecision>  ?var27 .  FILTER (  ( (  ?var27  =  "6" ) )  ) . } GROUP BY  ?var21   }
}
