
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 WHERE  { <http://www.wikidata.org/entity/Q11344>        <http://www.wikidata.org/prop/direct/P1086> ?var13  } LIMIT  10000  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 WHERE  { <http://www.wikidata.org/entity/Q11344>        <http://www.wikidata.org/prop/direct/P1086> ?var23  } LIMIT  10000  }
}
