
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var15  <http://schema.org/about>  ?var13 ;  <http://schema.org/isPartOf>  <https://de.wikipedia.org/> .   VALUES (  ?var16  ) {    (  <http://www.wikidata.org/entity/Q183>  )    (  <http://www.wikidata.org/entity/Q16957>  )    (  <http://www.wikidata.org/entity/Q713750>  )    (  <http://www.wikidata.org/entity/Q41304>  )    (  <http://www.wikidata.org/entity/Q7318>  )    (  <http://www.wikidata.org/entity/Q43287>  )   }   BIND (  YEAR (  ?var17  )  AS  ?var11 ).   ?var13  <http://www.wikidata.org/prop/direct/P569>  ?var17 ;  <http://www.wikidata.org/prop/direct/P21>  ?var12 ;  <http://www.wikidata.org/prop/direct/P27>  ?var16 . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var25  <http://schema.org/about>  ?var23 ;  <http://schema.org/isPartOf>  <https://de.wikipedia.org/> .   VALUES (  ?var26  ) {    (  <http://www.wikidata.org/entity/Q183>  )    (  <http://www.wikidata.org/entity/Q16957>  )    (  <http://www.wikidata.org/entity/Q713750>  )    (  <http://www.wikidata.org/entity/Q41304>  )    (  <http://www.wikidata.org/entity/Q7318>  )    (  <http://www.wikidata.org/entity/Q43287>  )   }   BIND (  YEAR (  ?var27  )  AS  ?var21 ).   ?var23  <http://www.wikidata.org/prop/direct/P569>  ?var27 ;  <http://www.wikidata.org/prop/direct/P21>  ?var22 ;  <http://www.wikidata.org/prop/direct/P27>  ?var26 . } GROUP BY  ?var21  ?var22   }
}
