
SELECT * WHERE {
{ SELECT DISTINCT ?var11  ?var12  ?var13  ?var14  ?var15  ?var16  ?var17  WHERE {   ?var18  <http://www.wikidata.org/prop/direct/P39>  <http://www.wikidata.org/entity/Q11696> .   ?var18  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var11  )  =  "en" ) )  ) .   ?var19  <http://www.wikidata.org/prop/direct/P26>  ?var18 .   ?var19  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12 .  FILTER (  ( (  LANG (  ?var12  )  =  "en" ) )  ) .   ?var18  <http://www.wikidata.org/prop/direct/P18>  ?var15 .   ?var19  <http://www.wikidata.org/prop/direct/P18>  ?var16 .   ?var18  <http://www.wikidata.org/prop/direct/P1971>  ?var13 .  FILTER (  ( (  ?var13  >= "2"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var14  <http://www.wikidata.org/prop/direct/P40>  ?var18 .   ?var14  <http://www.wikidata.org/prop/direct/P21>  <http://www.wikidata.org/entity/Q6581072> .   ?var18  <http://www.wikidata.org/prop/direct/P2097>  ?var17 . }  }
SIMILARITY JOIN ON ( ?var17 ) ( ?var27 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21  ?var22  ?var23  ?var24  ?var25  ?var26  ?var27  WHERE {   ?var28  <http://www.wikidata.org/prop/direct/P39>  <http://www.wikidata.org/entity/Q11696> .   ?var28  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var21  )  =  "en" ) )  ) .   ?var29  <http://www.wikidata.org/prop/direct/P26>  ?var28 .   ?var29  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22 .  FILTER (  ( (  LANG (  ?var22  )  =  "en" ) )  ) .   ?var28  <http://www.wikidata.org/prop/direct/P18>  ?var25 .   ?var29  <http://www.wikidata.org/prop/direct/P18>  ?var26 .   ?var28  <http://www.wikidata.org/prop/direct/P1971>  ?var23 .  FILTER (  ( (  ?var23  >= "2"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) .   ?var24  <http://www.wikidata.org/prop/direct/P40>  ?var28 .   ?var24  <http://www.wikidata.org/prop/direct/P21>  <http://www.wikidata.org/entity/Q6581072> .   ?var28  <http://www.wikidata.org/prop/direct/P2097>  ?var27 . }  }
}
