
SELECT * WHERE {
{ SELECT DISTINCT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var11 <http://www.wikidata.org/prop/P1087>/<http://www.wikidata.org/prop/qualifier/P585> ?var12 .   ?var11 <http://www.wikidata.org/prop/direct/P570> ?var14   FILTER ( ?var12 > ?var14 )  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var21 <http://www.wikidata.org/prop/P1087>/<http://www.wikidata.org/prop/qualifier/P585> ?var22 .   ?var21 <http://www.wikidata.org/prop/direct/P570> ?var24   FILTER ( ?var22 > ?var24 )  } GROUP BY ?var21  }
}
