
SELECT * WHERE {
{ SELECT ?var11Label ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var12  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5119> .   ?var12  ?var11  ?var14 .  FILTER (  ( (  ?var14  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var11Label   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21Label ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var22  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5119> .   ?var22  ?var21  ?var24 .  FILTER (  ( (  ?var24  > "0"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )  ) . } GROUP BY  ?var21Label   }
}
