
SELECT * WHERE {
{ SELECT ?var11 ( COUNT (* ) AS  ?var12  ) WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var13  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var14  <http://www.wikidata.org/prop/direct/P69>  ?var13 .   ?var14  <http://www.w3.org/2000/01/rdf-schema#label>  ?var15 .  FILTER (  ( (  LANG (  ?var15  )  =  "es" ) )  ) .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) )  ) .   ?var14  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var16  <http://www.wikidata.org/prop/direct/P57>  ?var14 .   ?var16  <http://www.w3.org/2000/01/rdf-schema#label>  ?var17 .  FILTER (  ( (  LANG (  ?var17  )  =  "es" ) )  ) .   ?var16  <http://www.wikidata.org/prop/direct/P577>  ?var18 . } GROUP BY  ?var11  LIMIT 100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT (* ) AS  ?var22  ) WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var23  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var24  <http://www.wikidata.org/prop/direct/P69>  ?var23 .   ?var24  <http://www.w3.org/2000/01/rdf-schema#label>  ?var25 .  FILTER (  ( (  LANG (  ?var25  )  =  "es" ) )  ) .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) )  ) .   ?var24  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var26  <http://www.wikidata.org/prop/direct/P57>  ?var24 .   ?var26  <http://www.w3.org/2000/01/rdf-schema#label>  ?var27 .  FILTER (  ( (  LANG (  ?var27  )  =  "es" ) )  ) .   ?var26  <http://www.wikidata.org/prop/direct/P577>  ?var28 . } GROUP BY  ?var21  LIMIT 100  }
}
