
SELECT * WHERE {
{ SELECT ?var11  ?var12 ( COUNT ( ?var13  ) AS  ?var14  ) WHERE {   ?var15  <http://schema.org/isPartOf>  ?var13 .   ?var13  <http://wikiba.se/ontology#wikiGroup>  "wiktionary".   ?var15  <http://schema.org/name>  ?var16 ;  <http://schema.org/about>  ?var11 .  FILTER (  ( !( CONTAINS (  ?var16 , ":" ) ) )  ) .  FILTER (  ( (  ?var11  !=  <http://www.wikidata.org/entity/Q5296>  ) )  ) .   ?var11  <http://wikiba.se/ontology#sitelinks>  ?var12 . } GROUP BY  ?var11  ?var12   }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22 ( COUNT ( ?var23  ) AS  ?var24  ) WHERE {   ?var25  <http://schema.org/isPartOf>  ?var23 .   ?var23  <http://wikiba.se/ontology#wikiGroup>  "wiktionary".   ?var25  <http://schema.org/name>  ?var26 ;  <http://schema.org/about>  ?var21 .  FILTER (  ( !( CONTAINS (  ?var26 , ":" ) ) )  ) .  FILTER (  ( (  ?var21  !=  <http://www.wikidata.org/entity/Q5296>  ) )  ) .   ?var21  <http://wikiba.se/ontology#sitelinks>  ?var22 . } GROUP BY  ?var21  ?var22   }
}
