
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14 .   ?var11  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var15  <http://www.wikidata.org/prop/direct/P69>  ?var11 .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var16 .   ?var15  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var17  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11424> .   ?var17  <http://www.wikidata.org/prop/direct/P57>  ?var15 .   ?var17  <http://www.wikidata.org/prop/direct/P577>  ?var18 .   ?var17  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12 .  FILTER (  ( (  LANG (  ?var14  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var16  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var12  )  =  "es" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24 .   ?var21  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var25  <http://www.wikidata.org/prop/direct/P69>  ?var21 .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var26 .   ?var25  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var27  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11424> .   ?var27  <http://www.wikidata.org/prop/direct/P57>  ?var25 .   ?var27  <http://www.wikidata.org/prop/direct/P577>  ?var28 .   ?var27  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22 .  FILTER (  ( (  LANG (  ?var24  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var26  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var22  )  =  "es" ) )  ) . } GROUP BY  ?var21   }
}
