
SELECT * WHERE {
{ SELECT ?var11 (COUNT(?var11) AS ?var12) WHERE  { _:b0  <http://wikiba.se/ontology#qualifier> ?var11 .   ?var13 <http://www.wikidata.org/prop/P2302> _:b1 .   _:b1  <http://www.wikidata.org/prop/statement/P2302> <http://www.wikidata.org/entity/Q21514353> ;      ?var11         ?var14  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (COUNT(?var21) AS ?var22) WHERE  { _:b0  <http://wikiba.se/ontology#qualifier> ?var21 .   ?var23 <http://www.wikidata.org/prop/P2302> _:b1 .   _:b1  <http://www.wikidata.org/prop/statement/P2302> <http://www.wikidata.org/entity/Q21514353> ;      ?var21         ?var24  } GROUP BY ?var21  }
}
