
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var14  <http://www.w3.org/2000/01/rdf-schema#label>  ?var15 .   ?var14  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var12  <http://www.wikidata.org/prop/direct/P69>  ?var14 .   ?var12  <http://www.w3.org/2000/01/rdf-schema#label>  ?var16 .   ?var12  <http://www.wikidata.org/prop/direct/P1196>  ?var17 .   ?var17  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .  FILTER (  ( (  LANG (  ?var15  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var16  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var24  <http://www.w3.org/2000/01/rdf-schema#label>  ?var25 .   ?var24  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var22  <http://www.wikidata.org/prop/direct/P69>  ?var24 .   ?var22  <http://www.w3.org/2000/01/rdf-schema#label>  ?var26 .   ?var22  <http://www.wikidata.org/prop/direct/P1196>  ?var27 .   ?var27  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .  FILTER (  ( (  LANG (  ?var25  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var26  )  =  "es" ) )  ) .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) )  ) . } GROUP BY  ?var21   }
}
