
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   ?var14  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var14  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var14  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11 .   ?var15  <http://www.wikidata.org/prop/direct/P69>  ?var14 .   ?var15  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12 .   ?var15  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var16  <http://www.wikidata.org/prop/direct/P57>  ?var15 .   ?var16  <http://www.w3.org/2000/01/rdf-schema#label>  ?var17 .  FILTER (  ( (  LANG (  ?var11  )  =  "es" ) && (  LANG (  ?var12  )  =  "es" ) && (  LANG (  ?var17  )  =  "es" ) )  ) . } GROUP BY  ?var11   }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   ?var24  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q3918> .   ?var24  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q298> .   ?var24  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21 .   ?var25  <http://www.wikidata.org/prop/direct/P69>  ?var24 .   ?var25  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22 .   ?var25  <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q2526255> .   ?var26  <http://www.wikidata.org/prop/direct/P57>  ?var25 .   ?var26  <http://www.w3.org/2000/01/rdf-schema#label>  ?var27 .  FILTER (  ( (  LANG (  ?var21  )  =  "es" ) && (  LANG (  ?var22  )  =  "es" ) && (  LANG (  ?var27  )  =  "es" ) )  ) . } GROUP BY  ?var21   }
}
