
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> ;      <http://www.wikidata.org/prop/direct/P2102> ?var12 ;      <http://www.wikidata.org/prop/direct/P1108> ?var13 ;      <http://www.wikidata.org/prop/direct/P2067> ?var14  } LIMIT  100  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> ;      <http://www.wikidata.org/prop/direct/P2102> ?var22 ;      <http://www.wikidata.org/prop/direct/P1108> ?var23 ;      <http://www.wikidata.org/prop/direct/P2067> ?var24  } LIMIT  100  }
}
