
SELECT * WHERE {
{ SELECT ?var11 (  SUM ( ?var11  ) AS  ?var12  ) WHERE {   ?var13  <http://wikiba.se/ontology#propertyType>  ?var11 . } GROUP BY  ?var11  LIMIT 1000  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (  SUM ( ?var21  ) AS  ?var22  ) WHERE {   ?var23  <http://wikiba.se/ontology#propertyType>  ?var21 . } GROUP BY  ?var21  LIMIT 1000  }
}
