
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ?var12 ?var13 ?var14 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P54> <http://www.wikidata.org/entity/Q221525> ;      <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581097> ;      <http://www.wikidata.org/prop/direct/P19> ?var12 ;      <http://www.wikidata.org/prop/direct/P1350> ?var14 .   ?var12 <http://www.wikidata.org/prop/direct/P625> ?var13  }  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ?var22 ?var23 ?var24 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P54> <http://www.wikidata.org/entity/Q221525> ;      <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581097> ;      <http://www.wikidata.org/prop/direct/P19> ?var22 ;      <http://www.wikidata.org/prop/direct/P1350> ?var24 .   ?var22 <http://www.wikidata.org/prop/direct/P625> ?var23  }  }
}
