
SELECT * WHERE {
{ SELECT ?var11 ?var12 WHERE  { SELECT ?var11 (COUNT(?var13) AS ?var12)   WHERE    { ?var13 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q79007> ;        <http://www.wikidata.org/prop/direct/P17> ?var11 ;        <http://www.wikidata.org/prop/direct/P138> ?var14 .     ?var14 <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581097>    }   GROUP BY ?var11  }  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 WHERE  { SELECT ?var21 (COUNT(?var23) AS ?var22)   WHERE    { ?var23 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q79007> ;        <http://www.wikidata.org/prop/direct/P17> ?var21 ;        <http://www.wikidata.org/prop/direct/P138> ?var24 .     ?var24 <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581097>    }   GROUP BY ?var21  }  }
}
