
SELECT * WHERE {
{ SELECT ?var11 (SUM(?var12) AS ?var13) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q937857> ;      <http://www.wikidata.org/prop/P54> ?var14 .   ?var14 <http://www.wikidata.org/prop/statement/P54> ?var15 ;      <http://www.wikidata.org/prop/qualifier/P1351> ?var12  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 (SUM(?var22) AS ?var23) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q937857> ;      <http://www.wikidata.org/prop/P54> ?var24 .   ?var24 <http://www.wikidata.org/prop/statement/P54> ?var25 ;      <http://www.wikidata.org/prop/qualifier/P1351> ?var22  } GROUP BY ?var21  }
}
