
SELECT * WHERE {
{ SELECT (COUNT(?var11) AS ?var12) ?var13 WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q13442814> ;      <http://www.wikidata.org/prop/direct/P577> ?var14   BIND(year(?var14) AS ?var13)  } GROUP BY ?var13 LIMIT  10  }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT (COUNT(?var21) AS ?var22) ?var23 WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q13442814> ;      <http://www.wikidata.org/prop/direct/P577> ?var24   BIND(year(?var24) AS ?var23)  } GROUP BY ?var23 LIMIT  10  }
}
