
SELECT * WHERE {
{ SELECT ?var11 ( COUNT ( ?var12  ) AS  ?var13  ) WHERE {   VALUES (  ?var14  ) {    (  <http://www.wikidata.org/entity/Q11424>  )    (  <http://www.wikidata.org/entity/Q24862>  )    (  <http://www.wikidata.org/entity/Q20667187>  )    (  <http://www.wikidata.org/entity/Q226730>  )    (  <http://www.wikidata.org/entity/Q506240>  )   }   ?var11  <http://www.wikidata.org/prop/direct/P31>  ?var14 ;  <http://www.wikidata.org/prop/direct/P214>  ?var12 . } GROUP BY  ?var11   HAVING  ( (  ?var13  > "2"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ( COUNT ( ?var22  ) AS  ?var23  ) WHERE {   VALUES (  ?var24  ) {    (  <http://www.wikidata.org/entity/Q11424>  )    (  <http://www.wikidata.org/entity/Q24862>  )    (  <http://www.wikidata.org/entity/Q20667187>  )    (  <http://www.wikidata.org/entity/Q226730>  )    (  <http://www.wikidata.org/entity/Q506240>  )   }   ?var21  <http://www.wikidata.org/prop/direct/P31>  ?var24 ;  <http://www.wikidata.org/prop/direct/P214>  ?var22 . } GROUP BY  ?var21   HAVING  ( (  ?var23  > "2"^^<http://www.w3.org/2001/XMLSchema#integer>  ) )    }
}
