
SELECT * WHERE {
{ SELECT DISTINCT ?var11 ?var12 (count(*) AS ?var13) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q33999> ;      <http://www.wikidata.org/prop/direct/P166> ?var14 ;      <http://www.wikidata.org/prop/direct/P27> ?var12  } GROUP BY ?var11 ?var12 LIMIT  200  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 ?var22 (count(*) AS ?var23) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q33999> ;      <http://www.wikidata.org/prop/direct/P166> ?var24 ;      <http://www.wikidata.org/prop/direct/P27> ?var22  } GROUP BY ?var21 ?var22 LIMIT  200  }
}
