
SELECT * WHERE {
{ SELECT DISTINCT ?var11 (COUNT(?var12) AS ?var13) WHERE  { ?var14 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q33999> ;      <http://www.wikidata.org/prop/direct/P166> ?var12 ;      <http://www.wikidata.org/prop/direct/P27> ?var11  } GROUP BY ?var11  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT DISTINCT ?var21 (COUNT(?var22) AS ?var23) WHERE  { ?var24 <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q33999> ;      <http://www.wikidata.org/prop/direct/P166> ?var22 ;      <http://www.wikidata.org/prop/direct/P27> ?var21  } GROUP BY ?var21  }
}
