
SELECT * WHERE {
{ SELECT ?var11Label ( COUNT ( ?var11Label  ) AS  ?var12  ) WHERE {   ?var13  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var13  <http://www.wikidata.org/prop/direct/P27>  <http://www.wikidata.org/entity/Q794> .   ?var13  <http://www.wikidata.org/prop/direct/P21>  ?var11 .   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  ?var11Label .   ?var13  <http://www.w3.org/2000/01/rdf-schema#label>  ?var14Label .  FILTER (  ( (  LANG (  ?var11Label  )  =  "fa" ) )  ) .  FILTER (  ( (  LANG (  ?var14Label  )  =  "fa" ) )  ) . } GROUP BY  ?var11Label   }
SIMILARITY JOIN ON ( ?var12 ) ( ?var22 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21Label ( COUNT ( ?var21Label  ) AS  ?var22  ) WHERE {   ?var23  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .   ?var23  <http://www.wikidata.org/prop/direct/P27>  <http://www.wikidata.org/entity/Q794> .   ?var23  <http://www.wikidata.org/prop/direct/P21>  ?var21 .   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  ?var21Label .   ?var23  <http://www.w3.org/2000/01/rdf-schema#label>  ?var24Label .  FILTER (  ( (  LANG (  ?var21Label  )  =  "fa" ) )  ) .  FILTER (  ( (  LANG (  ?var24Label  )  =  "fa" ) )  ) . } GROUP BY  ?var21Label   }
}
