
SELECT * WHERE {
{ SELECT ?var11  ?var12Label  ?var13  WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q6256> ;  <http://www.w3.org/2000/01/rdf-schema#label>  ?var12Label ;  <http://www.wikidata.org/prop/direct/P2132>  ?var13 .   ?var13  <http://www.wikidata.org/prop/direct/P585> "2015"^^<http://www.w3.org/2001/XMLSchema#integer> . }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22Label  ?var23  WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q6256> ;  <http://www.w3.org/2000/01/rdf-schema#label>  ?var22Label ;  <http://www.wikidata.org/prop/direct/P2132>  ?var23 .   ?var23  <http://www.wikidata.org/prop/direct/P585> "2015"^^<http://www.w3.org/2001/XMLSchema#integer> . }  }
}
