
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  WHERE {   ?var11  <http://www.wikidata.org/prop/direct/P485>  <http://www.wikidata.org/entity/Q964035> .   ?var11  <http://www.wikidata.org/prop/direct/P18>  ?var12 .   ?var11  <http://www.wikidata.org/prop/direct/P2021>  ?var13 .   ?var11  <http://www.wikidata.org/prop/direct/P18>  ?var14 . }  }
SIMILARITY JOIN ON ( ?var13 ) ( ?var23 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  WHERE {   ?var21  <http://www.wikidata.org/prop/direct/P485>  <http://www.wikidata.org/entity/Q964035> .   ?var21  <http://www.wikidata.org/prop/direct/P18>  ?var22 .   ?var21  <http://www.wikidata.org/prop/direct/P2021>  ?var23 .   ?var21  <http://www.wikidata.org/prop/direct/P18>  ?var24 . }  }
}
