
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) WHERE  { ?var13 <http://www.wikidata.org/prop/direct/P106> ?var11 ;      <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q222> .   ?var12 <http://schema.org/about> ?var11 ;      <http://schema.org/isPartOf> <https://sv.wikipedia.org/>  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) WHERE  { ?var23 <http://www.wikidata.org/prop/direct/P106> ?var21 ;      <http://www.wikidata.org/prop/direct/P27> <http://www.wikidata.org/entity/Q222> .   ?var22 <http://schema.org/about> ?var21 ;      <http://schema.org/isPartOf> <https://sv.wikipedia.org/>  } GROUP BY ?var21 ?var22  }
}
