
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(DISTINCT ?var13) AS ?var14) WHERE  { ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q27020041> ;      <http://www.wikidata.org/prop/direct/P31> ?var12 ;      <http://www.wikidata.org/prop/direct/P3450> ?var13   FILTER ( ?var12 != <http://www.wikidata.org/entity/Q27020041> )   FILTER ( ?var12 != ?var13 )  } GROUP BY ?var11 ?var12 HAVING ( ?var14 > 1 )  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(DISTINCT ?var23) AS ?var24) WHERE  { ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q27020041> ;      <http://www.wikidata.org/prop/direct/P31> ?var22 ;      <http://www.wikidata.org/prop/direct/P3450> ?var23   FILTER ( ?var22 != <http://www.wikidata.org/entity/Q27020041> )   FILTER ( ?var22 != ?var23 )  } GROUP BY ?var21 ?var22 HAVING ( ?var24 > 1 )  }
}
