
SELECT * WHERE {
{ SELECT ?var11  ?var12  ?var13  ?var14  ?var15  WHERE {   ?var11  <http://www.w3.org/2000/01/rdf-schema#label>  "Apple"@en .   ?var11  <http://www.wikidata.org/prop/direct/P31>  ?var12 .   ?var12  <http://www.wikidata.org/prop/direct/P279>  <http://www.wikidata.org/entity/Q783794> .   ?var11  <http://www.wikidata.org/prop/direct/P17>  ?var16 .   ?var16  <http://www.wikidata.org/prop/direct/P159>  ?var13 .   ?var11  <http://www.wikidata.org/prop/direct/P2139>  ?var14 .   ?var11  <http://www.wikidata.org/prop/direct/P856>  ?var15 . }  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21  ?var22  ?var23  ?var24  ?var25  WHERE {   ?var21  <http://www.w3.org/2000/01/rdf-schema#label>  "Apple"@en .   ?var21  <http://www.wikidata.org/prop/direct/P31>  ?var22 .   ?var22  <http://www.wikidata.org/prop/direct/P279>  <http://www.wikidata.org/entity/Q783794> .   ?var21  <http://www.wikidata.org/prop/direct/P17>  ?var26 .   ?var26  <http://www.wikidata.org/prop/direct/P159>  ?var23 .   ?var21  <http://www.wikidata.org/prop/direct/P2139>  ?var24 .   ?var21  <http://www.wikidata.org/prop/direct/P856>  ?var25 . }  }
}
