
SELECT * WHERE {
{ SELECT ?var11 ?var12 ?var13 ?var14 ?var15 ?var16 ?var17 ?var18 ?var19 WHERE  { BIND(concat(?var14, " , ", ?var16) AS ?var15)   ?var11 <http://www.w3.org/2000/01/rdf-schema#label> "Apple"@en ;      <http://www.wikidata.org/prop/direct/P31> ?var12 .   ?var12 <http://www.wikidata.org/prop/direct/P279> <http://www.wikidata.org/entity/Q783794> .   ?var11 <http://www.wikidata.org/prop/direct/P17> ?var16 ;      <http://www.wikidata.org/prop/direct/P159> ?var14 ;      <http://www.wikidata.org/prop/direct/P3362> ?var17 ;      <http://www.wikidata.org/prop/direct/P856> ?var18 ;      <http://www.wikidata.org/prop/direct/P1128> ?var19 ;      <http://www.wikidata.org/prop/direct/P452> ?var13  } LIMIT  1  }
SIMILARITY JOIN ON ( ?var17 ) ( ?var27 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 ?var23 ?var24 ?var25 ?var26 ?var27 ?var28 ?var29 WHERE  { BIND(concat(?var24, " , ", ?var26) AS ?var25)   ?var21 <http://www.w3.org/2000/01/rdf-schema#label> "Apple"@en ;      <http://www.wikidata.org/prop/direct/P31> ?var22 .   ?var22 <http://www.wikidata.org/prop/direct/P279> <http://www.wikidata.org/entity/Q783794> .   ?var21 <http://www.wikidata.org/prop/direct/P17> ?var26 ;      <http://www.wikidata.org/prop/direct/P159> ?var24 ;      <http://www.wikidata.org/prop/direct/P3362> ?var27 ;      <http://www.wikidata.org/prop/direct/P856> ?var28 ;      <http://www.wikidata.org/prop/direct/P1128> ?var29 ;      <http://www.wikidata.org/prop/direct/P452> ?var23  } LIMIT  1  }
}
