
SELECT * WHERE {
{ SELECT ?var11 ?var12 (COUNT(?var13) AS ?var14) WHERE  { { BIND(year(?var15) AS ?var12)    ?var11 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424> ;       <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q130232> ;       <http://www.wikidata.org/prop/direct/P577> ?var15 ;       <http://www.wikidata.org/prop/direct/P161> ?var13 .    ?var13 <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581072>   }   FILTER ( 2010 < ?var12 )  } GROUP BY ?var11 ?var12  }
SIMILARITY JOIN ON ( ?var14 ) ( ?var24 )
TOP %d DISTANCE %s AS ?d 
{ SELECT ?var21 ?var22 (COUNT(?var23) AS ?var24) WHERE  { { BIND(year(?var25) AS ?var22)    ?var21 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424> ;       <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q130232> ;       <http://www.wikidata.org/prop/direct/P577> ?var25 ;       <http://www.wikidata.org/prop/direct/P161> ?var23 .    ?var23 <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581072>   }   FILTER ( 2010 < ?var22 )  } GROUP BY ?var21 ?var22  }
}
